### ISSUE TITLE
Test Dart 3

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_client_sdk#1012]
### Is your feature request related to a problem? Please describe.

Dart 3 is presently in beta, and is likely to become the next stable release in a matter of weeks.

But... it introduces a number of breaking changes (especially around null safety) that are likely to be (even) more disruptive than the Dart 2.12 release that introduced null safety.

Those breaking changes can be expected to impact our dependencies as well as our own code.

### Describe the solution you'd like

A longer than usual lived feature branch that uses the Dart 3 beta.

**Comment by gkc** [comment]
Resolved by #1030
