### ISSUE TITLE
Unhandled Exception crash when TCP/RESET is received.

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#1022]
### Describe the bug

On Starlink and many other NAT'ed networks the TCP handling can be a little harsh and the firewal/nat can send TCP RESET packets to break TCP connections.

I think that is the cause here as if I use Starlink i see crashes of the at_client  :

```
Unhandled exception:
SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 92a7c219-e2eb-5f50-ac23-d7acba106cf5.swarm0002.atsign.zone, port = 64831
```

If I use SierraTel my local Telco I see none or very few...

But the at_client should be able to recover not crash in this situation..

### Steps to reproduce

1. I am not able to reprooduce the issue outside of my personal set up as yet

This effects longstanding at_clients like sshnpd more than anything else..

### Expected behavior

TCP session can crash but the at_client should not!

Currently the "solution" is to put the client software in a shell loop or have daemon to restart after a crash whcih is a little ugly !

### Smartphones

all

### Were you using an atApplication when the bug was found?

sshnpd

**Comment by gkc** [comment]
Both @cconstab and I feel that this may be coming from the socket that the sync service is using, as we haven't encountered the issue when we run programs with a NoOpSyncService. But to be clear, this is just guesswork right now

**Comment by gkc** [comment]
@cconstab Some progress ... I have been running a whole bunch of tests and have reproduced many times now - mostly with clients which are using sync - however I also reproduced this problem today with an at_talk version which was not using sync. So - the sync connection springing into life and doing stuff might be a common trigger, but the actual problem is elsewhere.

**Comment by gkc** [comment]
Have diagnosed the issue and am testing the fix.

**Comment by gkc** [comment]
Estimate 2SP to close this out during PR63
