### ISSUE TITLE
SyncService is not exported in at_client_mobile.dart

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#1027]
### Describe the bug

I noticed that SyncService is not exported in at_client_mobile.dart, and had a couple of questions related to it:
- Is there an explicit reason it's not exported or is it just something that's never come up
- If it's something that's never come up are there any reasons not to export it?

### Steps to reproduce

N/A

### Expected behavior

N/A

**Comment by gkc** [comment]
> * Is there an explicit reason it's not exported or is it just something that's never come up

No explicit reason that I'm aware of

> * If it's something that's never come up are there any reasons not to export it?

Not that I'm aware of. @sitaram-kalluri @murali-shris @VJag how about you?

**Comment by sitaram-kalluri** [comment]
One of the reasons is, In order to simplify the process of keeping the client and server in sync, with the aim of reducing the complexity for mobile app developers, the "sync" function is not exported. Instead, the responsibility for syncing was assigned to the "at_client" module.

**Comment by xavierchanth** [comment]
The way I see it, there are two patterns devs might follow:

1. chaining the call
```dart
atClient.syncService.sync();
```

2. storing an instance
```dart
SyncService ss = atClient.syncService;
// other code
ss.sync();
// maybe other stuff happens before sync is called again
ss.sync();
```

We are exposing the syncService via `atClient.syncService` but the class itself is not exposed in the scope, so atm 2 doesn't work. If there are no functional issues with storing the instance, I suggest that we export syncService for a couple of reasons:

- From the perspective of a dev less familiar with the SDK, providing it in scope makes it easier to use built-in tooling to find the class definition / documentation. I would be confused if I try to do `SyncService ss = atClient.syncService` and get an error under `SyncService`
- It is easier to teach in the docs if I can be verbose about the class
