### ISSUE TITLE
Invalid Syntax when running multiple get calls back to back

### ISSUE THREAD

**Issue by jtmuller5** [atsign-foundation/at_client_sdk#103]
I have an authenticated AtClient and if I try to get an AtKey once everything works fine:

```
getNoteFromKey('@donkeypainful82:note_55b853e0-955e-11eb-9509-b7ac56496923@caribouillegal96');

 Future<void> getNoteFromKey(String key) async {
    AtKey atKey = AtKey.fromString(key);
    atKey.sharedBy = AtUtils.formatAtSign(atKey.sharedBy);

    try {
      String newNote = await atProtocolService.get(atKey);
     
      if (newNote != null) {
        Note note = Note.fromJson(jsonDecode(newNote));

        print('Server value: ' + newNote.toString());
        if (note != null) {
          notes.insert(0, note);
        }
      }
    } on UnAuthenticatedException catch (e) {
      print('auth error: ' + e.message);
    } on AtLookUpException catch (e) {
      print('get note error: ' + e.errorMessage);
    }

    notifyListeners();
  }

Future<String> get(AtKey atKey) async {
    atKey.metadata = Metadata()
    ..isCached = false;
    var result = await atClientImpl.get(atKey);
    return result.value;
  }
```

But if I run the same method back-to-back like this:

```
    getNoteFromKey('@donkeypainful82:note_55b853e0-955e-11eb-9509-b7ac56496923@caribouillegal96');
    getNoteFromKey('@donkeypainful82:note_55b853e0-955e-11eb-9509-b7ac56496923@caribouillegal96');
```

I get an AtLookUpException with the error "Invalid syntax : Invalid syntax. e.g lookup:location@bob".

The same thing happens if I run the get call in a loop like this:
```
theirNotes.forEach((key) async {
      getNoteFromKey('@donkeypainful82:note_55b853e0-955e-11eb-9509-b7ac56496923@caribouillegal96');
    });
```

This is making it impossible to get read multiple keys at once.

**Comment by naresh0689** [comment]
Hi Joe,

We have to use await before getNoteFromKey method call as it returns future.

Regarding the second part of the issue,
theirNotes.forEach((key) async {
      getNoteFromKey('@donkeypainful82:note_55b853e0-955e-11eb-9509-b7ac56496923@caribouillegal96');
    });

We have to use Future.forEach instead of List.forEach 
Ex:

Future.forEach(theirNotes, (key) async {
    var result = await getNoteFromKey('@donkeypainful82:note_55b853e0-955e-11eb-9509-b7ac56496923@caribouillegal96');
  });

**Comment by jtmuller5** [comment]
Thanks @naresh0689! I wasn't aware of the Futrue.forEach syntax but that worked! I can close this issue.
