### ISSUE TITLE
Ability to run component state checks upon app resume

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#1032]
### Describe the bug

An issue occurred where monitor died in an emulator instance of an app, and monitor did not restart itself.

So far, the issue is not reproducible in a pure dart environment.

### Expected behavior

A potential solution in at_client_mobile would be to listen for the app resume and force a check to see if monitor needs restarting. More generally, we should add a method in the AtClient interface which apps can call when they resume from background, to ensure that various things are in the right state - e.g. connections to the atServer including the monitor connection

See also #1036

**Comment by gkc** [comment]
@XavierChanth @ksanty was this discussed (e.g. at an architecture call) and was it agreed it should be closed?

**Comment by xavierchanth** [comment]
We discussed at sprint planning, and I said we could close it since we still have #1036 to capture the work
