### ISSUE TITLE
Invalid or corrupted pad block issue while sharing a file with a new contact

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#1057]
### Describe the bug

In atMospherePro when a new contact is added and a file is shared with the newly created contact, There's an Invalid or corrupted pad block issue

### Steps to reproduce

1. First , clone the code from the branch "ui_redesign" branch of atMospherePro
2. Then Run the app and add a new contact
3. And then select the newly created contact and share a file

### Expected behavior

There should not be any pad block exceptions

### Screenshots

 SEVERE|2023-06-09 16:09:01.607824|EncryptionUtil|Error while decrypting value: Invalid argument(s): Invalid or corrupted pad block
I/flutter (22587): WARNING|2023-06-09 16:09:01.611390|SyncService (@aquamarine659)|Exception occurred when setting conflict info for @banana75:shared_key@aquamarine659 | Exception: Invalid argument(s): Invalid or corrupted pad block
I/flutter (22587): FINER|2023-06-09 16:09:02.541007|SyncService (@aquamarine659)|Informing 2 listeners of SyncProgress{atSign: @aquamarine659, syncStatus: SyncStatus.success, isInitialSync: false, startedAt: 2023-06-09 10:39:00.025813Z, completedAt: 2023-06-09 10:39:02.539274Z, message: null, keyInfoList:[KeyInfo{key: senthistory_v2.mospherepro@aquamarine659, syncDirection: SyncDirection.remoteToLocal , conflictInfo: null, commitOp: CommitOp.UPDATE_ALL}, KeyInfo{key: @banana75:shared_key@aquamarine659, syncDirection: SyncDirection.remoteToLocal , conflictInfo: ConflictInfo{remoteValue: null, localValue: null, errorOrExceptionMessage: Exception occurred when setting conflict info for @banana75:shared_key@aquamarine659 | Exception: Invalid argument(s): Invalid or corrupted pad block}, commitOp: CommitOp.UPDATE_ALL}, KeyInfo{key: @banana75:shared_key@aquamarine659, syncDirection: SyncDirection.localToRemote , conflictInfo: null, commitOp: CommitOp.UPDATE_ALL}, KeyInfo{key: shared_key.banana75@aquamarine659, syncDirection: SyncDir

### Smartphones

- Device: [e.g. Samsung Galaxy]
- OS: [e.g. Android]

### Were you using an atApplication when the bug was found?

atmospherePro

**Comment by gkc** [comment]
Thanks for this @purnimavenkatasubbu . Looks like it shouldn't be impacting the app itself, can you confirm?

@sitaram-kalluri - we can see `Exception occurred when setting conflict info for @Banana75:shared_key@aquamarine659` ... the exception is because it's trying to decrypt 'shared_key' using an AES key but shared_keys are encrypted using the RSA key. We should not be attempting to decrypt 'shared_key' records in the usual way. Can you look into a fix for this?

**Comment by purnimavenkatasubbu** [comment]
> Thanks for this @purnimavenkatasubbu . Looks like it shouldn't be impacting the app itself, can you confirm?
> 
> @sitaram-kalluri - we can see `Exception occurred when setting conflict info for @Banana75:shared_key@aquamarine659` ... the exception is because it's trying to decrypt 'shared_key' using an AES key but shared_keys are encrypted using the RSA key. We should not be attempting to decrypt 'shared_key' records in the usual way. Can you look into a fix for this?

Yes Gary, It's not impacting the app

**Comment by sitaram-kalluri** [comment]
> Thanks for this @purnimavenkatasubbu . Looks like it shouldn't be impacting the app itself, can you confirm?
> 
> @sitaram-kalluri - we can see `Exception occurred when setting conflict info for @Banana75:shared_key@aquamarine659` ... the exception is because it's trying to decrypt 'shared_key' using an AES key but shared_keys are encrypted using the RSA key. We should not be attempting to decrypt 'shared_key' records in the usual way. Can you look into a fix for this?

Sure Gary, Will fix this issue.
