### ISSUE TITLE
APKAM - ability to receive offline notifications

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#1076]
### Is your feature request related to a problem? Please describe.

APKAM enroll implementation works fine on server side.
Client side notification was tested using
https://gist.github.com/murali-shris/55d1d67a4510bed1363d811140592444

The above code works fine, when the client is running and server receives enroll request.

If client is offline and if server receives enroll request, once the client is started notifications should get received.

### Describe the solution you'd like

* check whether offline notifications can be received using notificationService.subscribe

### Additional context

server branch:
https://github.com/atsign-foundation/at_server/tree/apkam_enroll
demo steps:
1. Cram auth - alice using cram secret

2. enroll request from cram authenticated client

enroll:request:appName:wavi:deviceName:pixel:namespaces:[wavi,rw;buzz,rw]:apkamPublicKey:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg1THrbmEpXMDXUtci4GBNaARF2ghWYz6tC5PcO8oyjqioDwlp7lVZcufhgZGD2Dd5j124vyx8t0qlTP/LObK8WvgvLOY5NqUCOgYBv0VufVzOr6xrsNKVEKC9GzMkMbUfFwBVYHeeIg3IKeGTyxB+qHQIAa2gLZCBKX8EsLTGliQmkv2J96umaFTsS/juwxw9nSVpsMIwCcg6hA3njVbjR1p5o9mZ3lVw57GOHzkdyGXXBgKzNvBRXBSDOkNCulxoixrydqWD8sLc8AERQoWCUwSWITTS0YE/jFL8fH2zWupjJ510JmoIf2L2MJsiFFUCtRIRTWSIHs1/cXZiIEvhQIDAQAB

//check request type in value json

3. pkam using enroll id 

pkam:enrollApprovalId:74587b6c-046e-48e6-bd13-39870d674276:<signature>

4. generate APKAM keypair for new client

5. get totp from authenticated client - totp:get

6. open new ssl client and send enroll request with totp

enroll:request:appName:buzz:deviceName:pixel:namespaces:[buzz,rw]:totp:854187:apkamPublicKey:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBjiWEoHyhKFFbPysx7D2fd7RLKMFu9jrj4wn6NpRbd0im3kdO17tahJP6gV+GrAuS0Al8xvt+9XiwPvnMTs29uV3SOaov/M1r2GKclBwCozM/ps3LPlfB7ofIr9Bxo7DVRxRUUqpQLzP0XUDzwP8nkSmvO/XWA1gFLFcMzRpBOlm+R0HLowZzUJXXZwdNhCYr+NkjptxpdikDteKbReXC/twUsxA4mtaP8YR6nCZftb85IEfDZx3aJ8CZLlmpzZbEOsDzR7BBu9IGl0unXLIBuintwUEIp8vRKV8EP1KmRgiqXzso0JNpc+zztaOojh0YdTH8KqJx90e+ft39RuPwIDAQAB

7. pkam using enroll id 

pkam:enrollApprovalId:03fd2f26-ea64-461c-bfb1-db5c3024654f:

**Comment by sitaram-kalluri** [comment]
When starting the client and fetching the offline notifications, the notifications related to APKAM enrollment are not being returned; this is because Tin the secondary server, the NotificationType.self is not being written to the keystore and hence the notification is being written to the monitor connection.

The issue is fixed and changes are pushed in the following commit: https://github.com/atsign-foundation/at_server/commit/474800a5bf24dffb60c8d69a571c3ec1e40c4d89

**Comment by murali-shris** [comment]
Changes merged to trunk and persistence secondary  v3.0.54 published
