### ISSUE TITLE
Re-establishment of outbound connection takes time & socket exception

### ISSUE THREAD

**Issue by nitesh2599** [atsign-foundation/at_client_sdk#109]
As the outbound connection is checked at an interval of 5 mins. So, if connection is out-bounded 1 min after a check, then it will take 4 mins more to reestablish the connection.
Any notification in between that time gets lost.

Sometimes we receive a Socket Exception. Not sure how to handle it & if it has any issues in the app.

![Screenshot 2021-04-07 at 12 40 24 PM](https://user-images.githubusercontent.com/74917928/113825695-ee165500-979e-11eb-9cee-8c571777df14.png)

**Comment by murali-shris** [comment]
Issue is fixed in "stream_encryption" branch and currently being tested

**Comment by sachins-geekyants** [comment]
after auto restart of outbound connection , I am getting socket exception

<img width="668" alt="Screenshot 2021-04-19 at 12 58 45 PM" src="https://user-images.githubusercontent.com/74917871/115230934-9d094800-a132-11eb-9f5a-a608458ca717.png">

**Comment by murali-shris** [comment]
issue fixed in sdk_refactoring branch. Keeping this issue open till code is available in trunk

**Comment by nitesh2599** [comment]
Created a new updated issue for this https://github.com/atsign-foundation/at_client_sdk/issues/216.
