### ISSUE TITLE
Authentication issue for same atsign on multiple devices

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_client_sdk#11]
Atsign used: @test_ga5 on staging server
For server logs, testing time: 16 Dec - 4:45pm to 5:30pm IST
Three devices (simulators) used

1. CRAM authentication on Device A and saved a copy of backup keys - everything smooth
2. Paired the second device, Device B with the backup keys - everything smooth
3. Added a contact each on Device A & B. Preference was sync IMMEDIATE, but had to restart the app to get the two devices in sync i.e. show up both the contacts added.
4. Deleted the atsign from Flutter keychain of Device B
5. Reset the atsign from the atsign website.
6. Tried CRAM on device B:
`flutter: error here =>  Instance of 'UnAuthenticatedException'
flutter: Instance of 'UnAuthenticatedException'
flutter: outbound finish handler called
flutter: INFO|2020-12-16 17:13:04.464424|SyncManager|verbResult:data:5
flutter: error here =>  Exception updating entry:Hive error updating entry to commit log:HiveError: The same instance of an HiveObject cannot be stored in two different boxes.
flutter: Exception updating entry:Hive error updating entry to commit log:HiveError: The same instance of an HiveObject cannot be stored in two different boxes.`
7. Restarted app on Device A:
`Error in authenticating: ACTIVATE`
8. Tried CRAM authentication on Device A:
`flutter: Error in authenticating: Instance of 'UnAuthenticatedException'`
9. Tried restore with the older backup keys on both Device A & Device B:
`flutter: Error in authenticateWithAESKey => Instance of 'UnAuthenticatedException'`
10. Tried CRAM with app on a third device, Device C. Everything smooth and was able to save the backup keys.
11. Tried restore on Device A and Device B with the new backup keys. Authentication was successful and landed on home page.
12. Tried to access contacts on all three devices, all of them failed:
`flutter: error here => Invalid argument(s): Unsupported block type for private key: 18`
![image](https://user-images.githubusercontent.com/12222326/102348398-de90b780-3fc7-11eb-96d8-0b7e5b629aad.png)

**Comment by murali-shris** [comment]
@purnimavenkatasubbu please check whether this issue is reproducible  in latest build

**Comment by purnimavenkatasubbu** [comment]
Tested the above scenario once with @persona and then with @buzz. Now There was no issue and I was able to authenticate to the app and check all the details.

**Comment by murali-shris** [comment]
@sarika01 are you still facing this issue ?

**Comment by murali-shris** [comment]
@Sameeraja-Bharathula please update status on this

**Comment by Sameeraja-Bharathula** [comment]
Tested with @wavi and seems to be working fine. Will test with @rrive application.

**Comment by Sameeraja-Bharathula** [comment]
Tested with @rrive application. Everything seems to be working fine. The step 3 is also working fine. Sync will happen only if any put or delete operation is made. Added contact 1 on device A and with adding contact 2 on device B. It synced both contact1 and contact2. Similarly on device A added some event then it synced all contacts.
