### ISSUE TITLE
Stream transfer callback is not called

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_client_sdk#111]
In atmosphere basic, after a stream transfer initiation, the byte transfer call get the number of byte transferred but the stream completion callback is not called.
<img width="1433" alt="Screenshot 2021-04-07 at 2 05 30 PM" src="https://user-images.githubusercontent.com/12222326/113836621-adbcd400-97aa-11eb-89cb-26048f5f8209.png">

**Comment by sarika01** [comment]
There is no error in the app logs. After the "sending stream receive" log, the app just stays idle for a long time.

**Comment by murali-shris** [comment]
@sarika01 how many bytes are you receiving ? in the log I see total file size is 2604784..Are you getting these many bytes at the receiver ?

**Comment by sarika01** [comment]
I didn't track it. But, in the simulator I am seeing this temp file which is incomplete transfer of 46.9Mb


![Simulator Screen Shot - iPhone 8 - 2021-04-07 at 18 48 30](https://user-images.githubusercontent.com/12222326/113872846-e328e800-97d1-11eb-9a20-5e62def53c8d.png)

**Comment by sarika01** [comment]
There is one issue of file size being transferred i.e. test_transfer of 19 bytes was successful (This is on current dev_env branch changes). Then there is other random issue (on master / published package) where one image is successfully transferred and fails for another in similar scenario (i.e. file transferred in bytes is visible but completion callback is not called).

**Comment by murali-shris** [comment]
fixed and pushed to dev_env branch

**Comment by sarika01** [comment]
@murali-shris Issue is resolved with the latest code on dev_env branch.

**Comment by murali-shris** [comment]
bug found by Sarika in transferring multiple files is fixed in dev_env..Closing this issue.
