### ISSUE TITLE
Add dependency review action to at_client_sdk, at_widgets, at_libraries

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#1111]
This check in sshnoports failed: https://github.com/atsign-foundation/sshnoports/actions/runs/6045296008/job/16405133280?pr=414

After investigating, it's a transitive dependency used by at_onboarding_flutter and at_client (and image, but that's not our package).
We would have caught this vulnerability sooner if we did these checks on our other packages.

**Comment by gkc** [comment]
There is a ticket open on the `archive` repo https://github.com/brendan-duncan/archive/issues/276
