### ISSUE TITLE
Multiple file transfer throws exception

### ISSUE THREAD

**Issue by rishabhv1509** [atsign-foundation/at_client_sdk#112]
When trying to send multiple files in @mosphere pro this exception is thrown
![Screenshot 2021-04-07 at 4 24 03 PM](https://user-images.githubusercontent.com/16508786/113855467-b074f480-97bd-11eb-872e-d2d8fd01b864.png)

**Comment by rishabhv1509** [comment]
![Screenshot 2021-04-07 at 4 36 26 PM](https://user-images.githubusercontent.com/16508786/113856846-6856d180-97bf-11eb-84ba-07fd73e2aec1.png)

**Comment by rishabhv1509** [comment]
![Screenshot 2021-04-07 at 4 54 41 PM](https://user-images.githubusercontent.com/16508786/113858951-f59b2580-97c1-11eb-9813-cf00f4b54a1e.png)

**Comment by sarika01** [comment]
The multiple file transfer is now moved to Filebin and not using stream.
