### ISSUE TITLE
Status of shared data

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#113]
- [x] Code changes
- [x] Unit testing
- [x] QA

**Comment by ksanty** [comment]
https://github.com/atsign-company/server/issues/13

**Comment by murali-shris** [comment]
Have to merge PR from feature branch to trunk

**Comment by purnimavenkatasubbu** [comment]
Tested with sdk_refactoring branch. I could see the shared key status as local_updated, remote_updated, shared_with_notifier, Shared_with_llookup

LOCAL_UPDATED

Metadata{ttl: null, ttb: null, ttr: null,ccd: null, isPublic: false, isHidden: false, availableAt : null, expiresAt : null, refreshAt : null, createdAt : 2021-07-22 06:24:42.315807Z,updatedAt : 2021-07-22 06:24:42.315844Z,isBinary : null, isEncrypted : null, isCached : false, dataSignature: null, sharedKeyStatus: LOCAL_UPDATED}

REMOTE_UPDATED:

{"key":"@ sitaram:pincode@ murali","data":"634509","metaData":{"createdBy":null,"updatedBy":null,"createdAt":"2021-07-22 06:31:53.060984Z","updatedAt":"2021-07-22 06:31:53.060984Z","availableAt":null,"expiresAt":null,"refreshAt":null,"status":"active","version":0,"ttl":null,"ttb":null,"ttr":null,"ccd":null,"isBinary":false,"isEncrypted":false,"dataSignature":null,"sharedKeyStatus":"REMOTE_UPDATED"}}

update:@ alice:facebook@ purnima purnima_123

SHARED_WITH_NOTIFIED:

llookup:all:@ alice:facebook@ purnima
data:{"key":"@ alice:facebook@ purnima","data":"purnima_123","metaData":{"createdBy":null,"updatedBy":null,"createdAt":"2021-07-22 07:49:20.385994Z","updatedAt":"2021-07-22 07:49:20.386198Z","availableAt":null,"expiresAt":null,"refreshAt":null,"status":"active","version":0,"ttl":null,"ttb":null,"ttr":null,"ccd":null,"isBinary":false,"isEncrypted":null,"dataSignature":null,"sharedKeyStatus":"SHARED_WITH_NOTIFIED"}}


SHARED_WITH_LOOKED_UP

@ alice@lookup:facebook@ purnima
data:purnima_123

llookup:all:@ alice:facebook@ purnima
data:{"key":"@ alice:facebook@ purnima","data":"purnima_123","metaData":{"createdBy":null,"updatedBy":null,"createdAt":"2021-07-22 07:49:20.385994Z","updatedAt":"2021-07-22 07:52:45.889860Z","availableAt":null,"expiresAt":null,"refreshAt":null,"status":"active","version":1,"ttl":null,"ttb":null,"ttr":null,"ccd":null,"isBinary":false,"isEncrypted":null,"dataSignature":null,"sharedKeyStatus":"SHARED_WITH_LOOKED_UP"}}
