### ISSUE TITLE
End2end tests that pass without being able to reach another atServer

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_client_sdk#1133]
### Describe the bug

`24 tests passed, 25 failed.` when ce2e1 couldn't connect to ce2e2 (and similarly ce2e3 & 4)

### Steps to reproduce

1. First I configure cicd atServers to connect to wrong atDirectory
2. Then I run end2end tests
3. And then many of them pass even though remote atServers are unreachable

https://github.com/atsign-foundation/at_client_sdk/actions/runs/6402358157/job/17384836340 provides an example

### Expected behavior

End2end tests should only pass when another atServer is involved.

Tests that don't need another atServer should be refactored into functional tests.

If the run time for functional tests gets too long we can break them into batches.

### Additional context

This happened whilst migrating the cicd atServers, and a bunch of them were pointed at the wrong root server and thus unable to connect to their opposite atServer
[at_client_logs_3653.zip](https://github.com/atsign-foundation/at_client_sdk/files/12803299/at_client_logs_3653.zip)

**Comment by purnimavenkatasubbu** [comment]
Updated the tests and raised a [PR](https://github.com/atsign-foundation/at_client_sdk/pull/1154) Only PR review and merge are pending. Updating it to 2SP

**Comment by purnimavenkatasubbu** [comment]
Tests have been refactored and PR merged to trunk. [PR](https://github.com/atsign-foundation/at_client_sdk/pull/1154)

**Comment by gkc** [comment]
Thank you @purnimavenkatasubbu !
