### ISSUE TITLE
Unable to sync "used" atSigns using trunk version of atBuzz

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#1139]
### Describe the bug

I wanted to demo atBuzz and cannot get it to sync in the emulator I see many errors but this one stands out

``` 
I/flutter ( 4881): SEVERE|2023-10-16 11:34:55.169796|SyncService (@happyclam)|Exception in sync 7703fbc5-d838-4627-9fbf-329aa8bfa715. Reason: Failed to syncData caused by
I/flutter ( 4881): Unable to fetch latest server commit id: Exception: 9a 
```

### Steps to reproduce

1. First I get the latest trunk of atbuzz
2. Then I run it in an Android emulator (ios/iphone build breaks with MASSIVE list of errors!)
3. And then try to onboard an atSign
4. Onboard seems OK but sync never works and asks me to reset atSign
5. Not sure if this is a bug in Lib or app but since this error above is in the lib I raised the issue here..
6. REALLy would like this solved so it can get into the demo in NYC and I need to record it ASAP (today)

### Expected behavior

Things just work!

### Were you using an atApplication when the bug was found?

atBuzz (trunk)

**Comment by cconstab** [comment]
Video example...

https://github.com/atsign-foundation/at_client_sdk/assets/6131216/6d6b2be6-859e-444e-ac08-38da4cba4026

**Comment by ksanty** [comment]
Currently troubleshooting root cause

**Comment by VJag** [comment]
Observations so far:

1. For @happyclam, all of the data is properly synced for regex '.atbuzz|atconnections' using a test client
2. Purnima could reproduce the issue with the buzz app, where she saw contacts not being synced
3. Observed decryption issues in logs while running the app, however they are not present when synced using the test client

**Comment by VJag** [comment]
From app logs:

SEVERE|2023-10-16 18:51:15.602306|EncryptionUtil|Error while decrypting value: Invalid argument(s): Invalid or corrupted pad block
I/flutter ( 2011): INFO|2023-10-16 18:51:15.603355|AtContactsImpl|atconnections.anthony.contacts.happyclam does not exist in keystore

However, sync completes by skipping over any bad keys.

**Comment by purnimavenkatasubbu** [comment]
I debugged locally and found that there are no keys with '.atbuzz' namespace in the server

In happclam atsign, Contacts with at_contact.atbuzz regex is empty

@ happyclam@scan at_contact.atbuzz
data:[]

**Comment by sachins-geekyants** [comment]
@cconstab have you previously created data in atBuzz with `@happyclam`?

If yes, was it on the store test versions or locally ?

**Comment by VJag** [comment]
contacts in the buzz app are saved with at_contact.atbuzz namespace

In happclam atsign , Contacts with at_contact.atbuzz regex is empty

@happyclam@scan at_contact.atbuzz
data:[]


Whereas if I do a scan with only "atconnections" I get contacts with mosphere, mospherePro and wavi namespaces but not .atbuzz namespace. I think this is the reason

**Comment by ksanty** [comment]
@cconstab needs review please

**Comment by cconstab** [comment]
This was ckeared up with a bug Gary found and was commited a week or so back

Can be closed

**Comment by ksanty** [comment]
> This was ckeared up with a bug Gary found and was commited a week or so back
> 
> Can be closed

Yay!  Closed now.
