### ISSUE TITLE
Request / Response wrapper around notifications 

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#1159]
### Is your feature request related to a problem? Please describe.

A very common pattern we might find is that we want to request some data and poll for a response in realtime. In most situations it’s better to do this with ephemeral notifications, so it would be nice to write a library that does this for us.

### Describe the solution you'd like

We already do this in ssh no ports, it would be nice to extract this pattern and make it available to other use cases.

### Additional context

Additionally, it would be nice to support payload signing and public key caching for verification of the payload (also in sshnp)

**Comment by xavierchanth** [comment]
I am doing this from my phone... this was meant to be in the at_client_sdk repo... will move it when I'm back on my pc.

**Comment by gkc** [comment]
AtRpc in at_client provides request-response semantics over notifications. See recent sample usage in sshnoports branch gkc/feat/teams-enterprise-mdp
