### ISSUE TITLE
batch verb in at_client_sdk

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#119]
Naresh - need to discuss with Jagan @naresh0689

**Comment by ksanty** [comment]
https://github.com/atsign-foundation/at_client_sdk/issues/46

**Comment by VJag** [comment]
We do have a batch verb that we internally use in the SDK and it is not exposed to the app developers. The task is created to expose the batch to the app dev's but it did not make sense. We can close it and create a task if such a requirement arises as part of https://github.com/atsign-foundation/at_client_sdk/issues/470https://github.com/atsign-foundation/at_client_sdk/issues/470
