### ISSUE TITLE
Unable to compile due to error on at_client version 3.0.71

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#1205]
### Describe the bug

when compiling with 3.0.71 I get 
```
cconstab@tarial sshnoports % dart compile exe -o sshnp bin/sshnp.dart
../../../../../../../.pub-cache/hosted/pub.dev/at_client-3.0.71/lib/src/util/at_client_util.dart:36:52: Error: The argument type 'List<int>' can't be assigned to the parameter type 'Uint8List'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
    var signature = key.createSHA256Signature(utf8.encode(challenge));
                                                   ^
Error: AOT compilation failed
Generating AOT kernel dill failed!
cconstab@tarial sshnoports % 
``` 

but things are fine if I revert back to 3.0.70

### Steps to reproduce

1.  Try using 3.0.71 to compile a program
2. see error 

### Expected behavior

No errors

### Smartphones

-Dart

### Additional context

From @XavierChanth 

This is one of those weird bugs, where the dart linter fails with casting between Uint8List and List<int>. We need to explicitly cast the utf8 encoding to a Uint8List
What’s funny is that if you look at the docs for Utf8Codec utf8.encode is supposed to return a Uint8List, but the function it calls under the hood returns a List<int>: https://api.dartlang.org/stable/dart-convert/Utf8Codec-class.html

**Comment by gkc** [comment]
Resolved by #1206
