### ISSUE TITLE
at_client functional tests flakiness 2023-01-15

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#1207]
### Describe the bug

See https://github.com/atsign-foundation/at_client_sdk/actions/runs/7527814204/job/20488714969?pr=1206

### Steps to reproduce

See https://github.com/atsign-foundation/at_client_sdk/actions/runs/7527814204/job/20488714969?pr=1206

### Expected behavior

No flakiness

**Comment by gkc** [comment]
@sitaram-kalluri @purnimavenkatasubbu another one to look at 😀

**Comment by sitaram-kalluri** [comment]
@gkc : Sure Gary, will tale look and find the root cause. Thank you.

**Comment by sitaram-kalluri** [comment]
One hypothesis for the test failure is that the compaction job running in the background might have compacted the keys shortly before the compaction job triggered by the test began.

Here are the series of events:

1. The background compaction job started at "10:54:53".

```
INFO|2024-01-15 10:54:53.949693|AtClientCommitLogCompaction (@alice🛠)|Starting commit log compaction job running for every 11 minute(s)
```

2. The sync process is completed at 10:55:00

```
INFO|2024-01-15 10:55:00.926235|FunctionalTestSyncService|Completed sync| SyncStatus.success | localCommitId: 536 | ServerCommitId: 536 
```

3. The compaction job started by the test began before the sync and completed at "10:55:01", which is just after the sync.

```
{"atCompactionType":"ClientAtCommitLog","lastCompactionRun":"2024-01-15 
10:55:01.004321Z","compactionDurationInMills":"0","preCompactionEntriesCount":"30","postCompactionEntriesCount":"30","deletedKeysCount":"0"}
```

4. Then final sync is completed at 10:55:05

```
INFO|2024-01-15 10:55:05.076130|FunctionalTestSyncService|Completed sync| SyncStatus.success | localCommitId: 544 | ServerCommitId: 544 
```  

{"atCompactionType":"ClientAtCommitLog","lastCompactionRun":"2024-01-15 10:55:01.004321Z","compactionDurationInMills":"0","preCompactionEntriesCount":"30","postCompactionEntriesCount":"30","deletedKeysCount":"0"}
  Expected: <true>
    Actual: <false>

From the above snippet, the "compactionDurationInMills" shows 0 which evident that compaction triggered by the test run did not compact the keys.

**Comment by sitaram-kalluri** [comment]
The issue is fixed and the changes are available in "https://github.com/atsign-foundation/at_client_sdk/compare/trunk...refactor_compaction_job". Pending work is to raise PR and merge to trunk branch.
