### ISSUE TITLE
Need new version of at_client_mobile with at_chops dependency upgraded to ^2.0.0

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#1232]
### Describe the bug

Apps which use at_client_mobile are restricted to using at_client versions no later than 3.0.73

### Steps to reproduce

Try to flutter pub get for an app which is using at_client_mobile and at_client ^3.0.75

### Expected behavior

.

**Comment by VJag** [comment]
@srieteja Please talk to @murali-shris and @sitaram-kalluri to better understand what this is about. Its p0.

**Comment by purnimavenkatasubbu** [comment]
Raised a [PR](https://github.com/atsign-foundation/at_client_sdk/pull/1234). I also tested by updating package_info_plus with the apps, Facing an issue with wavi, Tagged the apps team for the same. Also mentioned in the comments of the PR.
https://github.com/atsign-foundation/at_client_sdk/pull/1234#discussion_r1482694351

**Comment by purnimavenkatasubbu** [comment]
published at_client_mobile:  v3.2.15
