### ISSUE TITLE
Collapse all working branches onto a trunk

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#124]
- [x] Move at_client_sdk to trunk - Sprint 10
- [x] Move at_server to trunk - Sprint 10
- [ ] Create a release tag and CI/CD,deployment pipeline - Sprint 10
- [x] Move libraries - TBD
- [x] Move widget to trunk - TBD

*List is not inclusive which we need to determine and plan

**Comment by ksanty** [comment]
- [ ]  Move at_client_sdk to trunk - Sprint 10
- [ ] Move at_server to trunk - Sprint 10
- [ ] Create a release tag and CI/CD,deployment pipeline - Sprint 10
- [ ] Move libraries - TBD
- [ ]  Move widget to trunk - TBD

**Comment by sitaram-kalluri** [comment]
Moved at_tools, at_libraries, at_server, at_client_sdk and at_widgets to trunk-based development.

**Comment by ksanty** [comment]
@kalluriramkumar @Sameeraja-Bharathula - Please update status as to when this will close.  We are moving to PR11 as of today.

**Comment by sitaram-kalluri** [comment]
The open item is carried to the next sprint - https://github.com/atsign-foundation/at_client_sdk/issues/129. Closing this issue.

**Comment by ksanty** [comment]
> The open item is carried to the next sprint - #129. Closing this issue. Thanks @kalluriramkumar
