### ISSUE TITLE
Deprecate notify:text 

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#1246]
### Is your feature request related to a problem? Please describe.

- Has been rendered obsolete as we can now send and receive fully ephemeral notifications

### Describe the solution you'd like

- Deprecate NotificationParams.forText
- Deprecate MessageTypeEnum.text in at_commons
- Deprecate the `messageType` getter in NotificationParams

**Comment by srieteja** [comment]
Implementation completed as part of attached PRs. Carrying it forward to get it reviewed.
