### ISSUE TITLE
Identify and minimise manual steps in the flow

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#127]
- [ ] Document the current manual steps

**Comment by ksanty** [comment]
- [ ] Document the current manual steps

**Comment by sitaram-kalluri** [comment]
Documented the manual steps that can be automated in the following link : https://docs.google.com/document/d/1fbZPobMMw2znSir-NxtpBm3AJ1sUHbuUl1Uih9iwbdA/edit#
