### ISSUE TITLE
Start collecting data on test pass/fail (whether tests are automated or not) so that we know which tests are the important ones that are catching bugs

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#128]
- [x] Purnima to come up with test cases

**Comment by purnimavenkatasubbu** [comment]
Documented the tasks which are automated and tests that usually fail. 

https://docs.google.com/spreadsheets/d/1kHCNSQvKT8KuqRlwlHlqCuTpuWEfCIPOKYkufxr6CNo/edit#gid=1520041462
