### ISSUE TITLE
Wrap up trunk based work

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#129]
- [ ] Cut releases for what we presently have on repo’s keeping in mind we are moving to a branch based trunk
- [ ] @colin prefers feature based releases (TBC)
- [ ] @kevin repo function will determine plan
- [ ] Release strategy
- [ ] Beginner friendly labels (Chris, Kim, Anthony)

**Comment by sitaram-kalluri** [comment]
1. The trunk branches are created in all following repository's : at_server, at_client_sdk, at_tools and at_libraries.
2. GitHub actions in place that you would dart lint rules and unit tests.
3. Run functional tests in at_client_sdk and at_server in GitHub actions
4. In at_server, build and push at_virtual_env and secondary docker image to docker hub.
5. Configure root URL for staging environment in GitHub Environments.
6. Configured different environments in atsign_pipeline_test to demonstrate the GitHub env.
