### ISSUE TITLE
Prepare for the next release and the mechanics for doing that

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#130]
- [ ] Need to decide what makes the next release the next release (mechanics)
- [ ] Need to decide how we cut a release from trunk to live (dev-stage-prod)
- [ ] Different from a patch, major and minor release

**Comment by sitaram-kalluri** [comment]
Add items related to the task in following link: https://docs.google.com/document/d/1fbZPobMMw2znSir-NxtpBm3AJ1sUHbuUl1Uih9iwbdA/edit
