### ISSUE TITLE
Need some e2e tests for APKAM-enrolled clients

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#1309]
### Describe the bug

We have no e2e tests right now which prove that APKAM-enrolled atsign_1 can successfully communicate with APKAM-enrolled atsign_2

### Expected behavior

Something like this in the e2e tests:
- create and then approve an APKAM enrollment for atSign1
- create and then approve an APKAM enrollment for atSign2
- Test put, get, delete (and their auto-notifications) atSign1 to atSign2 using APKAM to APKAM, APKAM to pkam, pkam  APKAM (in this shorthand terminology, pkam to pkam is what we currently test)
- Ideally refactor existing e2e tests to extract out the common stuff so we can then run them with whichever combination we want (current: pkam to pkam)

**Comment by gkc** [comment]
@sitaram-kalluri @murali-shris i have thoughts about how to do this easily, now that I've done this for NoPorts. I'll add a comment here over the weekend describing the approach

**Comment by sitaram-kalluri** [comment]
Currently, the E2E tests are running successfully. The unit tests are failing with dart beta version due to following dart issue: https://github.com/dart-lang/sdk/issues/55911#issuecomment-2153606884. Pending work is to update the dependencies and check if the issue is resolved.
