### ISSUE TITLE
Create a plan for null safety - Spike

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#131]

**Comment by murali-shris** [comment]
- [x] Run migration tool in at_tools
- [x] Run migration in at_lookup and at_server_status
- [x] Prepare plan to migrate rest of the repos

**Comment by murali-shris** [comment]
Null safety - migrated at_libraries/at_lookup, at_libraries/at_server_status
at_persistence_secondary has dependency on utf7 dart package which doesn’t have null safe version. Manually migrated utf7 and added it to at_libraries/dart_utf7. Facing compile issues after migrating at_persistence_secondary.

**Comment by murali-shris** [comment]
at_persistence migration done..at_client migration in progress and will be completed in sprint PR11
