### ISSUE TITLE
Update filebin2 and migrate to production AWS/GCP cluster

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#157]
Filebin2 is the backend for @mospherePro

- [x] Move to atsigncompany filebin2 dockerhub rep
- [x] create service on existing GCP cluster
- [x] create service on new AWS cluster
- [x] update to latest filebin2 binary 
- [x] test test test

**Comment by cpswan** [comment]
We have a fork now at [atsign-company/filebin2](https://github.com/atsign-company/filebin2). Default branch is trunk (leaving master to track upstream). A GitHub Action has been added to generate a Docker image at [atsigncompany/filebin2](https://hub.docker.com/repository/docker/atsigncompany/filebin2/tags?page=1&ordering=last_updated).

A new AWS account has been created for the EKS cluster and RDS database.

**Comment by cpswan** [comment]
@cconstab do you want this in GCP **and** AWS? I've been working on the assumption of **A** prod service.

**Comment by cconstab** [comment]
It was in AWS as it was free as we were building/testing. In an ideal world this should be in GCP as prod service. 

We generally leave AWS to test and backup

**Comment by cpswan** [comment]
@cconstab can you please enable billing for the Filebin2 project in GCP (or make me a billing account admin so I can do that).

**Comment by cpswan** [comment]
We now have two deployments with corresponding services and ingress running on the filebin2 GCP project:

* filebin2 - using older fork of code that works with Google Cloud Storage
* filebin2upstream - using later code that presents presigned URLs for S3

We're now ready for test,test,test

**Comment by cpswan** [comment]
Testing reported as complete (using hybrid GCP/S3 infrastructure) by @sarika01 in engineering stand-up.

I will turn down the pure GCP stack before closing this.

**Comment by cpswan** [comment]
Pure GCP services have been turned down.
