### ISSUE TITLE
Bypassing the cached version of a key

### ISSUE THREAD

**Issue by pcutillas** [atsign-foundation/at_client_sdk#169]
**Is your feature request related to a problem? Please describe.**

Sometimes it would be nice to get the most recent version of a key regardless of whether it is cached or not. Currently, this can be done using a low TTR, but because the TTR job runs once a day, it is functionally limited to multiples of 24 hours.

**Describe the solution you'd like**

I think the best solution would be to add an option to the get() function that allows you to bypass the cache (such as `...get(atKey, bypassCache: true)`). This would discourage using it on every key and minimize load on servers, while still allowing the functionality when it is needed.

**Describe alternatives you've considered**

- Having the TTR job run often
   - The problem with this is that irresponsible ttr setting could result in really heavy load on the servers.
- Adding a metadata option to ignore cache
   - This one would result in a key always bypassing the cache, which results both in less control on when to get a new version of the key and is heavier on the servers for the same reason.

**Comment by cpswan** [comment]
Thanks @Frenchman98 - this looks like a good one for our daily architecture discussion.

**Comment by VJag** [comment]
Thanks @Frenchman98. We will get back to you on this.

**Comment by pcutillas** [comment]
No problem, sounds good!

**Comment by gkc** [comment]
Not sure what ended up being done here. Going to bump into current sprint for discussion at least.

**Comment by gkc** [comment]
Work in this sprint will be to assess if there is a problem and how much of a problem it is.

**Comment by gkc** [comment]
This has come up again recently. Changing priority to High in the backlog.

**Comment by gkc** [comment]
See https://github.com/atsign-foundation/at_tools/pull/184

**Comment by murali-shris** [comment]
Update after sprint PR 36
* Pull request is ready in at_tools and at_server. End to end tests in server require more changes to support automation of starting and stopping secondary server as a part of test steps
* Changes for at_client is in branch bypass_cache. Pull request will be raised once at_commons is published and server released to prod

**Comment by murali-shris** [comment]
Published at_commons 3.0.16 and at_lookup 3.0.23.
Released server version 3.0.17a to canary.

**Comment by murali-shris** [comment]
No additional work to be done on this. Server latest version has to be released to prod.

**Comment by gkc** [comment]
@cconstab Canary https://github.com/atsign-foundation/at_server/releases/tag/c3.0.18a has been running for 10 days. Shall we roll out to production?

**Comment by cconstab** [comment]
I see no ships

**Comment by gkc** [comment]
@cconstab ummm, huh?

**Comment by cconstab** [comment]
Sorry yes I think we should push out.. Although there might be danger...

**Comment by gkc** [comment]
If we wait a little, I can write some more aggressive tests. The most intrusive changes were around notifications, I could do with adding some stress/break tests. How about I do that? And aim to release at the weekend of testing goes well

**Comment by murali-shris** [comment]
server version 3.0.18 released to prod

**Comment by murali-shris** [comment]
Reopening the issue since at client pull request was accidentally missed

**Comment by murali-shris** [comment]
pull request https://github.com/atsign-foundation/at_client_sdk/pull/591

**Comment by murali-shris** [comment]
pending tasks- fix end2end test issue , merge and publish

**Comment by murali-shris** [comment]
changes published. at_client v3.0.30
