### ISSUE TITLE
test refactored SDK code with @buzz

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#174]
- [x] at_buzz

**Comment by buzz** [comment]
> * [x]  @ buzz

Please stop mentioning my username. Thank you

**Comment by purnimavenkatasubbu** [comment]
Tested at_buzz with the sdk_refactoring branch. Currently, a bug on this is open 

[https://github.com/atsign-foundation/at_client_sdk/issues/179]
