### ISSUE TITLE
atsign.dev 2.0 : Content needed for Persistence under Services

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#183]
https://devstaging.atsign.wtf/docs/functional_architecture/services/

**Comment by sitaram-kalluri** [comment]
@anthonyvprakash:  Update the content for persistence under services. Below is the link to commit-id
1. https://github.com/atsign-foundation/atsign.dev/commit/030030de0ea998f777e89c7e727f3aa4e9483a46
2. https://github.com/atsign-foundation/atsign.dev/commit/030030de0ea998f777e89c7e727f3aa4e9483a46

**Comment by murali-shris** [comment]
@anthonyvprakash please add details on further documentation that has to be done

**Comment by anthonyvprakash** [comment]
@murali-shris @kalluriramkumar @TylerTrott  - Sorry for the delay. What we need here is an article similar to the other services that we have content for.

**Comment by anthonyvprakash** [comment]
@TylerTrott @Intiserahmed  - Please work on this ticket this Sprint PR19 and let us get it done.
