### ISSUE TITLE
atsign.dev 2.0 : Content needed for @protocol verbs

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#186]
https://devstaging.atsign.wtf/docs/functional_architecture/verbs/

- [x]  need to decide where we have content, sample code and descriptions for the verbs ( on Github or Pub.dev)
- [x]  Once decided we need content for all the verbs in the verb tree ( refer to https://docs.google.com/document/d/19A0g0AIJU3x2MiwgRgcguGmimrNLr03CdmZg0RdnU_Y/edit#heading=h.o9ky6rcbno3i)
- [x]  Once content is up, we need a script to import the content to the new page on the new dev site.

**Comment by naresh0689** [comment]
@anthonyvprakash  I have added verb definitions. Please have a look and let me know your comments.

**Comment by murali-shris** [comment]
PR for dart doc changes in server spec
https://github.com/atsign-foundation/at_server/pull/248/files

**Comment by murali-shris** [comment]
verb description changes merged to trunk.
PR for changes to link to dart docs
https://github.com/atsign-foundation/atsign.dev/pull/224/

**Comment by murali-shris** [comment]
at server spec version published to pub.dev 
https://pub.dev/packages/at_server_spec/versions/2.0.4
website changes merged to trunk branch of atsign.dev repo

**Comment by murali-shris** [comment]
@anthonyvprakash please close this issue, if all the requirements are met.
