### ISSUE TITLE
Shared key status isn't being updated to local_secondary

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#209]
**Describe the bug**
Status of the shared key is not being updated to the local_secondary and remote_secondary

**To Reproduce**
1. Run the test of shared_key_status in at_client tests
2. Then check the status of the key

**Expected behavior**
Status of the key should be updated to local_secondary and then to remote_Secondary

**Actual behavior**
Status is null

Branch: sdk_refactoring

**Comment by sitaram-kalluri** [comment]
Fixed the issues in the following commit id's
at_client_sdk: https://github.com/atsign-foundation/at_client_sdk/commit/e55164e8937dab9522416cb9852cfd359b9e6436
at_server: https://github.com/atsign-foundation/at_server/commit/36eaa813868d3488a3471b214c7427e615436c65

**Comment by purnimavenkatasubbu** [comment]
Tested the bug. Now I could see the status being updated.

Metadata{ttl: null, ttb: null, ttr: null,ccd: null, isPublic: false, isHidden: false, availableAt : null, expiresAt : null, refreshAt : null, createdAt : 2021-07-21 14:47:02.153599Z,updatedAt : 2021-07-21 14:47:02.153650Z,isBinary : null, isEncrypted : null, isCached : false, dataSignature: null, sharedKeyStatus: LOCAL_UPDATED}

llookup:all:@ sitaram:testing@ murali
data:{"key":"@ sitaram:testing@ murali","data":"6jWjbNr4Om8tHoBWWSXY2g==","metaData":{"createdBy":null,"updatedBy":null,"createdAt":"2021-07-21 14:47:02.379212Z","updatedAt":"2021-07-21 14:47:02.379212Z","availableAt":null,"expiresAt":null,"refreshAt":null,"status":"active","version":0,"ttl":null,"ttb":null,"ttr":null,"ccd":null,"isBinary":false,"isEncrypted":false,"dataSignature":null,"sharedKeyStatus":"REMOTE_UPDATED"}}
