### ISSUE TITLE
RSDK implementation with backward compatibility

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#218]
- [x]  skeleton code checkin
- [x]  put, putmeta, delete implementation
- [x] monitor implementation
- [x] notify implementation
- [x] testing

App bug dependencies:
Test link - [Decryption Issues](https://github.com/atsign-company/apps/issues/20)

**Comment by ksanty** [comment]
@murali-shris can you please add label(s) to this so we can better track?  TY

**Comment by murali-shris** [comment]
sync changes will be taken up as a part of 
https://github.com/atsign-foundation/at_client_sdk/issues/234

**Comment by murali-shris** [comment]
Code changes for monitor and notification merged to trunk
