### ISSUE TITLE
Add at_client functionality to at_cli

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#223]
Enable as much as possible in at_cli using the at_client lib.

Enabling encrypted put/get etc..

- [x] Add at_client_sdk as dependency.
- [x] Change Authentication mechanism to use .atkeys file instead of cram/pkam
- [x] Change authRequired and isPublic arguments to flags
- [x] Change Verbs implementation from at_lookup to at_client.
- [x] Add documentation where ever 
- [x] Dev testing
- [x] QA testing

**Comment by ksanty** [comment]
@cconstab can you please add label(s) so we can better track? TY

**Comment by naresh0689** [comment]
Attaching screenshots for referene.

**Comment by naresh0689** [comment]
![Screenshot from 2021-08-24 21-42-45](https://user-images.githubusercontent.com/10126219/130652546-a9d54fbe-72f3-47f2-a371-b0f605681739.png)

**Comment by naresh0689** [comment]
![Screenshot from 2021-08-24 21-42-37](https://user-images.githubusercontent.com/10126219/130652649-4b0a14d8-f60a-4939-a275-faa65c6a7263.png)

**Comment by naresh0689** [comment]
![Screenshot from 2021-08-24 21-42-23](https://user-images.githubusercontent.com/10126219/130652702-78efc6ed-c419-45c1-b9eb-49acd9193aa8.png)
