### ISSUE TITLE
Create some MVP level solutions for the Local Radio Station and Amateur Radio technical communities.

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#229]
- [x] MVP for monitor commercial LP FM 
- [x] Talk to leaders in the HAM world for ideas
- [x] develop MVP / opensource projects to kick start projects
- [x] Create demo wavi page [AI6BH](https://wavi.ng/@ai6bh)

**Comment by ksanty** [comment]
@cconstab can you please add a [label(s)](https://github.com/atsign-company/labels/labels) to this so we can better track status?  TY
