### ISSUE TITLE
sync improvements

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#234]

**Comment by murali-shris** [comment]
scope changed after discussion in architecture call.
* apps will no longer make periodic calls to server. instead server will send a notification with latest commit id
* existing stream sync will be removed

**Comment by murali-shris** [comment]
- [x] stats notification service
- [x] replace stream sync with new sync verb with limit
- [x] dev testing
- [x] update new sync on appsand test
