### ISSUE TITLE
at_client_sdk (at_client_mobile / at_client_flutter) should support desktop

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_client_sdk#241]
The sdk should move from flutter_keychain to support desktop version.

**Comment by ksanty** [comment]
@sarika01 can you please estimate sprint points here as well as assign a dev?  TY

**Comment by murali-shris** [comment]
@ksanty this requires a discussion in architecture call before we estimate

**Comment by nickelskevin** [comment]
Propose that we:
- maintain at_client_sdk as having no flutter depencies
- create a new package called at_client_flutter that provides support for both mobile and desktop
- maintain at_client_mobile as well for now, but plan to deprecate in favor of at_client_flutter

**Comment by cpswan** [comment]
@sarika01 is this closed by #322?

**Comment by sarika01** [comment]
No @cpswan . This is independent of that.

Changes have been made to use biometric_storage in place of flutter_keychain. Platform support for macos, windows and linux is now available in at_client_mobile: ^3.1.2

**Comment by gkc** [comment]
@sarika01 Can this ticket be closed?
