### ISSUE TITLE
RSDK: Data being lost while switching between the atsigns

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#258]
**Describe the bug**
Switching between multiple atsigns in the apps, leads to data not being shown in the app

**To Reproduce**
1. First I authenticate to the wavi app as atsign A and add some details
2. Then , Add another atsign into the app, Say atsign B
3. Now select the atsign A again all the data is lost

Note: restarting the app shows the data as it is  

**Expected behavior**
Data should be displayed correctly even while switching between multiple atsigns

**Screenshots**

https://user-images.githubusercontent.com/43639593/131808377-3a47549b-be68-46b5-9891-2823cdaa40a5.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS:Android
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  -  @ wavi

https://user-images.githubusercontent.com/43639593/131808377-3a47549b-be68-46b5-9891-2823cdaa40a5.mp4

**Additional context**

**Comment by sitaram-kalluri** [comment]
Investigated the issue, Seems like wavi is not refreshing on switching the atsign. Updated @charannnreddy on my observations. Adding @charannnreddy to the assignees list.

**Comment by purnimavenkatasubbu** [comment]
Tested the scenario with the latest fix branch switch_fix_sync. I'm able to switch between atsigns and able to see the data correctly.

https://user-images.githubusercontent.com/43639593/132186808-2887cafe-bf80-4da1-92d2-e35c08b207b0.mp4
