### ISSUE TITLE
Migrate from package:pedantic to package:lints

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_client_sdk#305]
**Describe the solution you'd like**

Per the guidance from [dart-lang/lints](https://github.com/dart-lang/lints#migrating-from-packagepedantic):

in each `pubspec.yaml`:

```diff
-  pedantic: ^1.11.0
+  lints: ^1.0.1
```

and in each `analysis_options.yaml`:

```diff
-include: package:pedantic/analysis_options.yaml
+include: package:lints/recommended.yaml
```

**Comment by con-mark** [comment]
can you assign to me I will do
