### ISSUE TITLE
New Client Code needs to be included in builds

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#318]
at_client 3.0.4

- [x] @ wavi                        
- [x] @ buzz
- [x] @ mospherpro
- [x] @ rrive

**Comment by ksanty** [comment]
@cconstab added this ticket.  Please add more detail if needed, also which dev will be working on.

**Comment by sarika01** [comment]
@ mospherePro and @ rrive have been updated to at_client 3.0.4 and published.

**Comment by sarika01** [comment]
@DivyaYadavareddy Please confirm on wavi and buzz.

**Comment by DivyaYadavareddy** [comment]
@ wavi and @ buzz have been updated to at_client 3.0.6 and published.

**Comment by cpswan** [comment]
Ticking off the last two and closing based on @DivyaYadavareddy update
