### ISSUE TITLE
sync enhancement - analysis and design

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#320]
- [x] Design work
- [x] Design plan

**Comment by murali-shris** [comment]
Analyse and design for the below scenarios
* syncing app updates when initial sync is running
* sync strategy when regex on sync changes

**Comment by VJag** [comment]
![sync_analysis](https://user-images.githubusercontent.com/20091120/141737253-f431d9ef-f85f-4f8b-a174-16f0d5878bf9.png)
[](url)

**Comment by VJag** [comment]
Based on my analysis, the secondary should support exposing the First and Last key that matches a regex so that SDK can go back in time ask for the entries.
