### ISSUE TITLE
Analyse decryption issues

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#321]
Analyse and come up with approach for below scenarios

- [ ] Public key changes
- [ ] Encryption key changes

**Comment by sitaram-kalluri** [comment]
Analyzed the decryption issues and below are the observations:
1. Trying to decrypt a null value.
2. The encryption shared key is not found.
Made defensive code fix to catch the error and return a proper message on the decryption is failing.

**Comment by ksanty** [comment]
@kalluriramkumar can you please update this ticket?  I think we said we would close this one and link to the new ticket.  Also, please use check boxes for lists, so we have a progress update against each ticket.  TY!!

**Comment by sitaram-kalluri** [comment]
Further on decryption issue, there is an open ticket on when atsign is reset, the encryption key changes and hence data fails in decrypt process. There is open ticket on the issue. Attaching the git-issue and closing this.

https://github.com/atsign-foundation/at_client_sdk/issues/115
