### ISSUE TITLE
self encryption key is not set for atsign

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#324]
**Describe the bug**
I onboarded with @ minorgettingplayed7 on @ mosphere pro , when tried to add contact I started getting exception in encryption service and contact was not added.

`Exception: Self encryption key is not set for atsign @minorgettingplayed7`

after resetting the keychain and onboarding again I did not got this issue and was able add contacts.
This behaviour was seen on multiple devices while testing. 

**Expected behavior**
contact should be added without any encryption exception.

**Screenshots**

![Screenshot 2021-11-08 at 12 01 22 PM](https://user-images.githubusercontent.com/74917871/140741661-c273f2d8-d8b8-4de4-82ea-8673bf3a409f.png)

**Were you using an @‎application when the bug was found?**
  - @ mosphere pro

--------------------------------------------------------------------------------------------------------------------

- [x]  Diagnosed (we understand how it’s happening )
- [x] Reproducible (may not always be true even when we know how to fix)
- [x] Fix identified 
- [x] Fix being worked on (PR expected to be raised April 6)
- [x] Fix verified by developer (should be in next released version of at_client package library)
- [x] Fix available in pub.dev (please provide package version)
- [x] Tested - fixed
- [ ] Tested - failed

**Comment by Gayathri-GA** [comment]
I have faced the similar issue, While I am trying to add contact on @mosphere pro app, The contacts is not getting added also it results below exception

<img width="900" alt="Screenshot 2022-03-14 at 5 20 25 PM" src="https://user-images.githubusercontent.com/60135944/158166331-d151413f-4ac6-43da-acac-0ecf92431f95.png">

**Comment by sitaram-kalluri** [comment]
Analysed the code and found the root cause of the issue. The issue occurs only in iOS devices. When an app in iOS is uninstalled the local storage gets cleared but the keychain remains as is. Hence, during onboarding the app gets the data from the key-chain manager. But in `onboard` method in `at_client_service.dart`, we do not have the logic to persist the keys from key-chain manager to local storage. 

As a temporary fix, calling `persistKeys` in onboard method in at_client_service.dart after line no. 220 resolved the issue.

**Comment by sachins-geekyants** [comment]
@kalluriramkumar is this fix available to test by pointing to any branch ?

**Comment by gkc** [comment]
@sachins-geekyants I just spoke to @kalluriramkumar - he has fix in local branch which resolves this, and he will be raising a PR shortly

**Comment by gkc** [comment]
Going to add this into the current sprint as it looks important to resolve for the next AtmospherePro release

**Comment by gkc** [comment]
@sachins-geekyants Sita's created the PR #473 branch https://github.com/atsign-foundation/at_client_sdk/tree/persist_keys

**Comment by gkc** [comment]
@kalluriramkumar previously in this ticket you said, "As a temporary fix, calling persistKeys in onboard method in at_client_service.dart after line no. 220 resolved the issue."

Does Sachin still need to do that, or does [this PR ](https://github.com/atsign-foundation/at_client_sdk/pull/473) fix the issue such that your suggested temporary fix is no longer needed?

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar previously in this ticket you said, "As a temporary fix, calling persistKeys in onboard method in at_client_service.dart after line no. 220 resolved the issue."
> 
> Does Sachin still need to do that, or does [this PR ](https://github.com/atsign-foundation/at_client_sdk/pull/473) fix the issue such that your suggested temporary fix is no longer needed?

This PR fixes the issue and the temporary fix is not needed.

**Comment by gkc** [comment]
@sachins-geekyants once you've done a test against at_client trunk to verify this fix, we can publish a new at_client package version which includes this fix

**Comment by sachins-geekyants** [comment]
It's working fine with the trunk branch.

**Comment by sitaram-kalluri** [comment]
The fix is published in at_client_mobile: ^3.1.12.
