### ISSUE TITLE
Pub.dev documentation at_client_mobile, at_client

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#337]
### Pub.dev content and (source)s - CHECKLIST OF TO DO's BELOW
All the content shown on pub.dev and where it comes from. 
Example: [Shelf](https://pub.dev/packages/shelf) (will point to one of our own once completed)

- Package name, version <pubspec.yaml>
- Published date (generated)
- Platform support (generated based on project structure)
- Tabbed navigation
  - Readme (note: initial content comes from readme.md) <github repo>
  - Changelog <github repo> example: [firebase_auth](https://pub.dev/packages/firebase_auth/changelog)
  - Example (github repo)
  - Installing (generated)
  - Versions (generated) <pubspec.yaml>
  - Scores (generated)
  - **Admin  (generated)
  - **Activity log (generated)

- Right column
  - Scores  (generated)
  - Publisher  (generated)
  - Metadata  <pubspec.yaml description>
  - Homepage <pubspec.yaml>
  - Repository (generated)
  - View/report issues (generated)
  - Documentation (generated)
    - Documentation url <pubspec.yaml>
    - API reference <generated>
  - License (github repo)
  - Dependencies (generated)
  - More (generated)

### All items to be completed:
- [x] Package should be implemented with rSDK
- [x] Include an example (sample) app based on at_app skeleton
- [x] Add example.md to explain how to run the sample app
- [x] Ensure the readme.md follows the best practice template (WIP)
- [x] Make sure and add in terms that will help get this package to the top of the search results 
- [x] Update changelog.md with clear description of the update
- [x] Bump the version as appropriate in pubspec.yaml for the package
- [x] Bump the version as appropriate in pubspec.yaml for the example
- [x] Check that the description is accurate in pubspec.yaml for the package
- [x] As appropriate, add a documentation link to atsign.dev for the package

**Comment by yahu1031** [comment]
Change versions, and changelogs, bump version for example, and package, adding links of atsign docs will be handled at the end of everything. atsign docs will be added when they are done. Necessary/important functions/methods usages were given in the readme file. Need more info regarding what needs to be added and what is not in the readme.

**Comment by yahu1031** [comment]
Documentation done and deployed to pub.dev
