### ISSUE TITLE
Sync failure for @mightysanddollar

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#340]
**Describe the bug**
while running @ mightysanddollar atsign with wavi.ng app and I am getting sync failure consistently.
```
flutter: syncStatus : Sync status: SyncStatus.failure lastSyncedOn: 2021-11-30 08:21:14.492196Z Exception: AT0025: FormatException: Unexpected end of input (at character 1)
^
```

where as with other atsign , sync is working fine.

**To Reproduce**
1. try running wavi.ng
2. onboard with mightysanddollar
3. check sync status

**Expected behavior**
sync should success.

**Were you using an @‎application when the bug was found?**
  - wavi.ng

**Comment by murali-shris** [comment]
@purnimavenkatasubbu please get the keys and replicate the issue

**Comment by purnimavenkatasubbu** [comment]
Tested the issue with the play store wavi.ng app. I could replicate the issue.

SEVERE|2021-12-14 11:26:23.093990|AtLookup|Error in remote verb execution Instance of 'UnAuthenticatedException'
I/flutter (20623): error in follows package init : AT0401: Client authentication failed
I/flutter (20623): syncStatus type : Sync status: SyncStatus.failure lastSyncedOn: 2021-12-14 05:56:27.210909Z Exception: AT0025: FormatException: Unexpected end of input (at character 1)
I/flutter (20623):
I/flutter (20623): ^

**Comment by murali-shris** [comment]
root cause is due to memory issue on server. Server is getting restarted and the initial sync response doesn't reach the client.
Removed logging of values for sync progressive verb handler
https://github.com/atsign-foundation/at_server/pull/440
Will push the above change to prod and then increase the memory limit for this atsign based on the outcome.

**Comment by sachins-geekyants** [comment]
Initial sync worked fine and I was able to get data for mightysanddollar atsign.
