### ISSUE TITLE
Failure to store public data within atsign

### ISSUE THREAD

**Issue by danielgoncalves25** [atsign-foundation/at_client_sdk#345]
**Describe the bug**
I am trying to store data within my atsign and make that data public for everyone. I am getting error code AT0003 Invalid syntax.

**To Reproduce**
This is the code where im creating the AtKey object and setting its attributes.
```
    var metaData = Metadata()..isPublic = true;

    var atKey = AtKey()
      ..key = nameController.text
      ..metadata = metaData
      ..namespace = NAMESPACE
      ..sharedWith = atSign;

    var success = await atClientManager.atClient
        .put(atKey, json.encode(articleJson), isDedicated: true);
```

**Screenshots**

![error DIY](https://user-images.githubusercontent.com/66567808/145462186-d2b44582-c779-4b4a-a530-f248695d4afb.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL API 30
 - OS: Android
 - Version unknown

**Were you using an @‎application when the bug was found?**
  - Creating my own app for the @platform

**Additional context**
Data is successful stored but not whenever I set isPublic attribute to true.

**Comment by cconstab** [comment]
@danielgoncalves25 sorry this is a little tricky and the error is not useful, we will raise a an enhancement ticket to make both of those a thing of the past...

But to the answer I will provide an example from one of my [apps](https://github.com/cconstab/catweb). In my case I am also adding some other metadata so the key times out after an hour.. 

The catch is that for public data you have to say isPublic, isEncrypted and share with null

Let us know if that fixes your problem...

```
var metaData = Metadata()
    ..isPublic = true
    ..isEncrypted = false
    ..namespaceAware = true
    // // one minute
    // ..ttl = 60000 ;
    // One Hour
    ..ttl = 3600000;

  var key = AtKey()
    ..key = 'public.' + hamradio.radioName
    ..sharedBy = currentAtsign
    ..sharedWith = null
    ..metadata = metaData;

   await atClient.put(key, jsonEncode(publichamradio));
```

**Comment by nickelskevin** [comment]
Also - you can remove isDedicated as it is being deprecated.
[/// Starting version 3.0.0 [isDedicated] is deprecated
](https://github.com/atsign-foundation/at_client_sdk/blob/472469e67d2f34fd38072dc19cc188ebf61ecc55/at_client/lib/src/client/at_client_spec.dart)

**Comment by nickelskevin** [comment]
Will categorize this as an enhancement request as follows:
We should consider adding additional information for Invalid syntax errors.

**Comment by gkc** [comment]
1) isPublic and isEncrypted are effectively inverses of each other. We should change code to enforce that and deprecate one of them (I’d suggest deprecating isEncrypted - this is an implicit developer expectation that things are always encrypted unless isPublic is set)
2) sharedWith is fully irrelevant when isPublic is true. We should either (a) actively prevent that combination or (b) just silently set sharedWith to null when isPublic is true, and explain in documentation. (a) is cleaner but is a breaking change; so I suggest (b), with a WARNing logged also

**Comment by ksanty** [comment]
@cconstab I put you on this issue card.  Please update if I got it wrong.  :)

**Comment by cconstab** [comment]
Not something I was going to fix in the code but I did answer the original question. Jagan/Murali/GKC this needs you guys to agree an approach to make the enhancement.. Might be worth opening a new ticket if this one is too confusing..

**Comment by gkc** [comment]
Hi @danielgoncalves25 - see [cconstab's suggestion above](https://github.com/atsign-foundation/at_client_sdk/issues/345#issuecomment-990441244) which should help you resolve your problem.

Have opened feature request #364 for a better API, and feature requests #365 and #366 for better guidance / protections when using the existing API

**Comment by cconstab** [comment]
Closing this ticket but noting that [ #364  ](https://github.com/atsign-foundation/at_client_sdk/issues/364)was opened
