### ISSUE TITLE
updates are not reflecting on wavi page for @mightysanddollar

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#371]
**Describe the bug**
Change on wavi app does not reflects on wavi website for mightysanddollar atsign. 

**To Reproduce**
1. Onboard on wavi with mightysanddollar
2. make any changes
3. changes does not reflect on wavi webpage

**Expected behavior**
Updates should sync with wavi webpage.

**Were you using an @‎application when the bug was found?**
  - @ wavi

**Additional context**
changes made with other atsigns are reflecting on webpage.

**Comment by Sardar1208** [comment]
I have tested this issue with @mightysanddollar. This is not reproducible now.

**Comment by gkc** [comment]
Closing as not reproducible
