### ISSUE TITLE
Missing keys in getAtKeys

### ISSUE THREAD

**Issue by nitesh2599** [atsign-foundation/at_client_sdk#377]
Lead: @yahu1031 

**Describe the bug**
The atsign `tina_she` created a key `custom_me_-_what_i’m_all_about.wavi` using the old wavi app and the new wavi app is not able to get that key in the `getAtKeys` call.

While the api used in the wavi website is able to get that key.

**To Reproduce**
1. Log in to the new wavi app (previously called wavi.ng) with atsign `tina_she`.
2. The key `custom_me_-_what_i’m_all_about.wavi` will not be visible in the app, while it will be available in https://directory.staging.atsign.wtf/@tina_she.

**Expected behavior**
The AtClient.getAtKeys() should return us the key `custom_me_-_what_i’m_all_about.wavi` along with all other keys.

**Screenshots**
Screenshots and screen recordings https://github.com/atsign-foundation/apps/issues/350

**Smartphone (please complete the following information):**
 - Device: iPhone 11 simuator
 - OS: iOS 14.5

**Were you using an @‎application when the bug was found?**
  - wavi app (previously called wavi.ng)

**Additional context**
The difference between this key and the keys that are loaded successfully is that this key has a `'` symbol in it.

**Comment by yahu1031** [comment]
Looks like this is not a `'`. It looks more similar, `’` which is a unicode character. Need to investigate it more. The scan verb gives us the key `custom_me_-_what_i’m_all_about.wavi@tina_she`. But when looking up in the core code it doesn't give it.

**Comment by yahu1031** [comment]
This is a similar issue that is happening with `@armadillocoffeesilky`. I have a key as zero-width whitespace. wavi.ng website is able to fetch it but not wavi app.

**Comment by sarika01** [comment]
@yahu1031 What is the fix or solution for this?

**Comment by yahu1031** [comment]
Started working on it @sarika01 will update you soon

**Comment by yahu1031** [comment]
@nitesh2599 Can you please check it now? Cause Latest changes are in canary and the atsign is also in canary.

**Comment by yahu1031** [comment]
@nitesh2599 Server logs need to be checked. I pinged @kalluriramkumar about it and he will LMK what was logged there.

**Comment by yahu1031** [comment]
![image](https://user-images.githubusercontent.com/35523357/152771039-b0a99435-360d-405e-9800-cb2970d9792f.png)
Here is the result after the fix

**Comment by gkc** [comment]
@yahu1031 You marked this Fixed and said
> Here is the result after the fix

How was the fix verified?

**Comment by yahu1031** [comment]
Sorry @gkc for not writing up anything. Cause, This was reproduced with collaboration with @purnimavenkatasubbu. And then later I was on leave and During that time @kalluriramkumar made some fixes and pushed to canary servers. As @tinashe404 atsign(@tina_she) was a canary atsign, It got fixed. Maybe Sitaram can give more info about it.

**Comment by sitaram-kalluri** [comment]
@gkc : I believe the following PR might have fixed the issue: [#492](https://github.com/atsign-foundation/at_server/pull/492)

**Comment by nitesh2599** [comment]
@yahu1031 I tested this now. On the device that already had `@tina_she` logged in (in which the issue was reported), that device is not able to get the `custom_me_-_what_i’m_all_about.wavi` key still.

Tried it on a new device and it was able to get the `custom_me_-_what_i’m_all_about.wavi` key.

**Comment by yahu1031** [comment]
Cache cleaning works I think

**Comment by yahu1031** [comment]
@nitesh2599 can we close this issue?

**Comment by nitesh2599** [comment]
Yes, I think we can. Thanks.
