### ISSUE TITLE
Not receiving notification after switching atsign

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#379]
Lead: @kalluriramkumar 

**Describe the bug**
If we have onboarded with @ a , we receive notification.
On switching to @ b , we still receive notifications.
If we switch back to @ a , we stop receiving notification.

**To Reproduce**
1. onboard with any atsign (@ a)
2. switch to second atsign (@ b)
3. switch back to @ a and we stopped receiving notifications.

**Expected behavior**
we should receive notifications at @ a .

**Were you using an @‎application when the bug was found?**
  - @ mosphere pro desktop

**Additional information**
On notification sender's side , we can see status as delivered.

**Comment by sarika01** [comment]
This is a blocker for apps functionality.

**Comment by murali-shris** [comment]
@sachins-geekyants is this issue appearing in mobile app as well?

**Comment by sachins-geekyants** [comment]
@murali-shris yes .

**Comment by murali-shris** [comment]
When atsign is switched instance of NotificationServiceImpl is not getting cleared from serviceMap.So when the same atsign is switched back again, monitor will not be started.Fixed the issue and pushed to "switch_atsign_bug" branch.
@sachins-geekyants please test from this branch

**Comment by sachins-geekyants** [comment]
@murali-shris I can still see this issue in "switch_atsign_bug" branch.

**Comment by sitaram-kalluri** [comment]
Moving the issue to PR30 and re-estimating to 1SP.

**Comment by murali-shris** [comment]
After switching atsign, monitor is getting started but sync is getting called from -1 and no stats notification is received via monitor which is an issue. Currently investigating this issue

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_client_sdk/pull/396
Awaiting app testing feedback from Purnima

**Comment by purnimavenkatasubbu** [comment]
Tested with the branch "switch_atsign_bug". was able to receive notifications after switching atsigns.

https://user-images.githubusercontent.com/43639593/153560437-e439b0db-b3bc-4973-9b47-e43d2f5bb837.mp4

**Comment by sachins-geekyants** [comment]
working fine with "switch_atsign_bug" branch.
