### ISSUE TITLE
publish packages for refactoring changes

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#381]
Lead: @kalluriramkumar (please update if labeled incorrectly)

Test and publish the packages in the below order
server:

- [x] at_commons
- [x] at_peristence_spec
- [x] at_persistence_secondary_server
- [x] deploy server with updated package version at_client
- [x] at_client 
- [x] at_client_mobile
- [ ] update widgets dependent on at_client to latest version

**Comment by sitaram-kalluri** [comment]
Published the packages of at_client for refactoring of get and decryption service
at_commons: 3.0.3
at_utils: 3.0.5
at_lookup: 3.0.7
at_persistence_secondary_server: 3.0.15
at_client: 3.0.9
at_client_mobile: 3.1.5
