### ISSUE TITLE
Atkey validation uptake

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#394]
Lead: @kalluriramkumar 

Uptake the AtKey Validation design.

- [x] Implement toString on the AtKey and its subclasses
- [x] Validate() on AtKey and its subclasses
- [x] Invoking validate in the key creation paths like "put and notify"
- [x] If we end up with existing characters that we do *_not_* wish to add to our allow list, then we need to decide what to do. It is certainly _possible_ for us to implement code to allow existing keys which break the rules to continue to exist, be retrieved, and even be updated, while preventing creation of any *new* keys, but this would be a *lot* of work.
- [x] Plug the validation into SDK and the server. (Question: Is there a staged rollout required here? e.g. first prevent any *_new_* 'bad' keys being created on the client side but allow 'get' on secondary to continue to work indefinitely for existing keys)

**Comment by sitaram-kalluri** [comment]
Burnt down 2 story points in PR-30. Carry over to next sprint.

**Comment by sitaram-kalluri** [comment]
Progress in PR-31
----------------------------
1. Completed implementing the toString method in AtKey and its sub-classes.
2. Updated the unit tests
3. Plugged in AtKey validations in at_client put method and notify method.

**Comment by sitaram-kalluri** [comment]
Ran the new AtKey validations on all the production @ Sign and following is the [link](https://docs.google.com/spreadsheets/d/1I31fBNl2-Hwc1guE-I8tjevL-mUsaBpV2qKHyeIr8fU/edit?usp=sharing) that has the special characters/emojis and keys that fail the with new validations.

Burnt  5 SP in Sprint PR-32

**Comment by gkc** [comment]
Thank you Sitaram this is *great* work! @cconstab @nickelskevin please take a look at the spreadsheet Sitaram created (link in previous comment) ... the number of invalid keys overall is quite low and, eyeballing the data, it looks like most of them are in at-signs of people within the company

**Comment by purnimavenkatasubbu** [comment]
Started testing atKey validation using at_client tests. Adding the scenarios to this [sheet](https://docs.google.com/spreadsheets/d/1rYmCmY6hrYeH72iKyGyloLtddzTnT1LwEL626n8mQ1U/edit?usp=sharing) as I'm testing it

**Comment by sitaram-kalluri** [comment]
Implemented the at_key validations for the put method . Following is the [PR](https://github.com/atsign-foundation/at_client_sdk/pull/492). Spent 8 SP's

**Comment by purnimavenkatasubbu** [comment]
Verified all the valid and invalid scenarios of atKeys using the atClient tests, wavi, and buzz apps and updated the [sheet](https://docs.google.com/spreadsheets/d/1rYmCmY6hrYeH72iKyGyloLtddzTnT1LwEL626n8mQ1U/edit#gid=1870842278) with the results.

**Comment by sitaram-kalluri** [comment]
The PR is merged to trunk branch  and yet to be published.

**Comment by sitaram-kalluri** [comment]
The changes are rolled back to release the fix related to last notification id. The changes are in exception chaining PR.

**Comment by sitaram-kalluri** [comment]
The changes are merged back to trunk on following PR's 
1. [PR-513](https://github.com/atsign-foundation/at_client_sdk/pull/513)
2. [PR-515](https://github.com/atsign-foundation/at_client_sdk/pull/515)

**Comment by sitaram-kalluri** [comment]
Moving to PR 39 to publish the changes

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client 3.0.26 version
