### ISSUE TITLE
Update archetype to new template

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_client_sdk#398]
Before we can update the Pub.dev unlisted packages, we need to update the Github [archetype](https://github.com/atsign-foundation/archetype).  See [example](https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client_mobile) for framework.

- [x] [Readme.md](https://github.com/atsign-foundation/archetype/blob/trunk/README.md)
- [x] [Contributing.md](https://github.com/atsign-foundation/archetype/blob/trunk/CONTRIBUTING.md)
- [x] Check logo (example [here](https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client_mobile))
- [x] Add badges (example [here](https://github.com/atsign-foundation/at_client_sdk/tree/trunk/at_client_mobile))

To be updated (by @XavierChanth):
- [x] [at_demo_data](https://github.com/atsign-foundation/at_demos/pull/40)
- [x] [at_contact & at_server_status](https://github.com/atsign-foundation/at_libraries/pull/166)
- [x] at_commons & at_utils
- [x] at_persistence_spec, at_persistence_secondary_server & at_server_spec

**Comment by cpswan** [comment]
archetype(s) have been updated, along with all the repos using them
