### ISSUE TITLE
Depend on biometric_storage ^4.0.0 in at_client_mobile

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#402]
**Describe the bug**
biometric_storage has a bug in ^3.0.0 that crashes when building with kotlin version >= 1.6.
This will allow support for kotlin 1.6

**To Reproduce**
1. First I pulled atsign-company/mwc_demo
2. Then I ran the app with commit id: 46bcb49b8907ad7ce9eb2203efceba981dafd08a
3. And then it fails to build

[Link to the original issue in biometric_storage](https://github.com/authpass/biometric_storage/issues/53)

**Expected behavior**
The app is able to build using kotlin version >= 1.6

**Screenshots**
![image](https://user-images.githubusercontent.com/33691921/153672135-d0c4781c-1fe1-4909-bec8-75f3c7c31a81.png)

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Windows 10

**Were you using an @‎application when the bug was found?**
mwc_demo

**Additional context**
N/A

**Comment by Intiserahmed** [comment]
The error goes away and build successfully when you upgrade your  kotlin version to 1.5.10. Which can be found in android/build.gradle.

The probable cause of this happening is biometric storage requires kotlin version greater 1.4 and old projects don't have that.

**Comment by yahu1031** [comment]
## INFO: ##
In case the latest kotlin version doesn't work, then having the same version as biometric_storage uses will work.

```gradle
buildscript {
    ext.kotlin_version = '1.5.21'
    // ... REST CODE ...
}
```
This will work.

**Comment by xavierchanth** [comment]
Closing stale bug, this one has been resolved by the above comment
