### ISSUE TITLE
APKAM continue SPIKE and start implementation

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#410]
We have analyzed various ideas for:

How apps can claim ownership of a namespace
How an @ app becomes known
Potential use of the secondary server for @ company can potentially solve some of the issues related to publishing and exchanging data with the apps.
Conclusions and next steps:

An @ app need not prove that it is a genuine @ app
@ app's writing to each other namespace is a separate problem that needs solving
All that is left now is to come up with spikes and sub-tasks around Colin's design and implement them in this sprint. This needs to be tracked through a separate task.

**Comment by murali-shris** [comment]
carry over to PR32. no updates in PR31

**Comment by murali-shris** [comment]
no work done in PR 36..carry over to PR 37

**Comment by ksanty** [comment]
@murali-shris is this a discussion item ticket for arch call?

**Comment by gkc** [comment]
Up to Colin / Kevin as to when we focus on this again

**Comment by gkc** [comment]
Closing this ticket as obsolete; APKAM impl is well under way now
