### ISSUE TITLE
Automatic sync not working on at_client: 3.0.10 / at_utils 3.0.6 onwards

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#418]
**Describe the bug**
When setting a AtKey and putting a value using at_client: 3.0.10 / at_utils 3.0.6 onwards no client sync is happening so no notification is sent and the receiving @ sign does not know about the shared information

**To Reproduce**
1. Using the MWC demo code use the previous version of the libs and everything works as it should
2. Then I updated to the newer versions and everything stops working and with weird sync results
3.  Moving back cures the issues
4.  The MWC demo and Snackbar use auto notiifications and hence if someone builds them with the latest libs they will not work!

**Expected behavior**
Auto Synch should work as it did in previous builds

**Video**

https://user-images.githubusercontent.com/6131216/155606320-d148726f-9206-4df8-818c-65746050bdaf.mp4

**Smartphone (please complete the following information):**
 - Dart SDK version: 2.16.1 (stable) (Tue Feb 8 12:02:33 2022 +0100) on "windows_x64"

**Were you using an @‎application when the bug was found?**
  - mwc demo

**Additional context**

**Comment by cconstab** [comment]
As a side note I watched the video and found/saw the '42' I changed it to '0' so that would zero out the dials at first rather than give a false reading..

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client : 3.0.12

**Comment by cconstab** [comment]
Suggest we leave this ticket open under we have end to end tests in place to check this works

**Comment by murali-shris** [comment]
end to end test to be taken up in PR 32
