### ISSUE TITLE
Decrypting notification values

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#435]
**Is your feature request related to a problem? Please describe.**
At the moment, the value in the notifications are not decrypted out of the box. The apps have to decrypt the notification value.

**Describe the solution you'd like**
Provide out of the box feature to decrypt the notification value.

**Comment by murali-shris** [comment]
draft PR.
https://github.com/atsign-foundation/at_client_sdk/pull/442
functional test added is not working. have to investigate further

**Comment by sitaram-kalluri** [comment]
Coding complete. Need to publish the changes. Adding - 1SP.

**Comment by murali-shris** [comment]
published 
at_client - 3.0.16
at_client_mobile - 3.1.12
