### ISSUE TITLE
Enhance the notify method to use the new encryption process

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#436]
**Is your feature request related to a problem? Please describe.**
At the moment notify method in the at_client uses the old encryption process.

**Describe the solution you'd like**
Replace the old encryption process with the new encryption process.

**Comment by murali-shris** [comment]
PR review done.at client will be published after next server release
https://github.com/atsign-foundation/at_client_sdk/pull/452/files

**Comment by murali-shris** [comment]
server release is pending..moving to next sprint

**Comment by murali-shris** [comment]
Published 
at_client 3.0.16
at_client_mobile 3.1.12
