### ISSUE TITLE
Cannot run at_client_mobile example app

### ISSUE THREAD

**Issue by Intiserahmed** [atsign-foundation/at_client_sdk#439]
**Describe the bug**
The at_client_mobile example app is not currently working due to it's missing env file.
![Screenshot 2022-03-08 at 7 40 50 PM](https://user-images.githubusercontent.com/57252940/157249285-660c09fb-cbd4-4dad-a75f-d0ea549fed16.png)

**To Reproduce**
Need to add the .env file .

**Comment by gkc** [comment]
@Intiserahmed can you point me at a repo with an app which has a .env file please

**Comment by gkc** [comment]
@kalluriramkumar maybe this issue has been caused by https://github.com/atsign-foundation/at_client_sdk/pull/433

**Comment by Intiserahmed** [comment]
> @kalluriramkumar maybe this issue has been caused by #433

yeah I believe this causing the issue.

**Comment by sitaram-kalluri** [comment]
As per the discussion with @gkc, we are not adding the `.env` file into the repository. The action item on this to make the user know that .env file is required either through the readme or describe in the error message.

**Comment by srieteja** [comment]
removed the .env file and have added a section in the readme.MD to demonstrate the use of an env file. As suggested in the PR, working on a method to alert the user/developer while building the app that there needs to be an env file. This will be achieved by throwing an exception that suggests the developer to use an env file.

**Comment by srieteja** [comment]
Necessary changes have been made. The app runs smoothly for me now. @Intiserahmed please take a look at the branch that has been linked to this ticket and see if it resolves the issue that was initially causing.

**Comment by srieteja** [comment]
Issues have been resolved and the changes have been merged to trunk in the PR linked to this ticket. Example app runs smoothly with the env file now.
