### ISSUE TITLE
.getKeys() does not provide a list with sharedWith parameter. 

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_client_sdk#440]
**Describe the bug**
The `.getKeys()` does not provide a list with sharedWith parameter. 

**To Reproduce**
1. First I sent a key using the `.put()` method.
```
    var key = AtKey()
      ..key = 'dude'
      ..sharedBy = currentAtsign
      ..sharedWith = '@wildgreen'
      ..metadata = metaData;

    await atClient.put(
      key,
      'duude',
    );
```
2. Then I retrieve a key using the `.get(key)` successfully
```
    var key = AtKey()
      ..key = 'dude'
      ..sharedBy = null
      ..sharedWith = '@wildgreen'
      ..metadata = metaData;

    var data = await atClient.get(key);
```
the result is 'duude'
3. And then I tried to retrieve a list of keys using the `.getKeys()` method but was unsuccessful.

```
    listData = await atClient.getKeys(
      regex: 'at_skeleton_app',
      sharedWith: '@wildgreen'
    );
```
The result is an empty list
4. 

**Expected behavior**
List of key that was shared with "@wildgreen".

**Screenshots**
Result when  a `sharedWith` parameter is provided
<img width="464" alt="getKeys with sharedWith parameter" src="https://user-images.githubusercontent.com/44856451/157356154-4ef75f8f-5e35-4cf0-81cf-960a4d8b5a13.png">

Result when a `sharedWith` parameter is not provided
<img width="1163" alt="getKeys without shareWith parameter" src="https://user-images.githubusercontent.com/44856451/157356356-0b347c7e-699f-42d0-a6b3-0db15c3628f3.png">

**Smartphone (please complete the following information):**
 - Device: Samsung S9+
 - OS: MacOS Monterey
 - Browser: NA
 - Version 12.0.1

**Were you using an @‎application when the bug was found?**
 No. I'm creating a new @application called at_dude

**Additional context**

**Comment by gkc** [comment]
@CurtlyCritchlow was this fixed or not a bug or ... ?

**Comment by CurtlyCritchlow** [comment]
It's not a bug. @cconstab explained that isPublic must be false in the metadata or the shareWith atSign will not be associated with the key. Maybe this should be mentioned in the documentation.

**Comment by gkc** [comment]
Ah yes. There's been a fair bit of work over the past couple of months around this part of the SDK as there are a few pitfalls like this (there still are, so we could keep backwards compatibility for now).

Most relevant would be https://github.com/atsign-foundation/at_tools/pull/133 which made various AtKey builders available.
