### ISSUE TITLE
at_client decryption_service/decryption_manager unhandled exception

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#443]
**Describe the bug**
When sending the service something that is not encrypted or badly formated results in uncaught exception

**To Reproduce**
1.  Set up a notification callback (with wrong regex)
2. Then caught call back and tried to decrypt the regaulr 15 second keep alive on the monitor
3. Decrypt fails and crashes program unless I catch in my code

**Expected behavior**
Exception should be caught in the SDK

My error in the regex 

 notificationService.subscribe(regex: 'blueamateurbinding').listen(

This should be 

 notificationService.subscribe(regex: 'blueamateurbinding@').listen(

To make sure I was looking at the namespace 'blueamateurbinding'

but that meant I was triggering the decrypt on the 15 second monitor and got this error  on this line of code

    var value = await decryptionService.decrypt(atKey, notification.value);

```
statsNotification.@blueamateurbinding
Unhandled exception:
FormatException: Invalid length, must be multiple of four (at character 4)
163
   ^

#0      _Base64Decoder.close (dart:convert/base64.dart:639:7)
#1      Base64Decoder.convert (dart:convert/base64.dart:510:13)
#2      Base64Codec.decode (dart:convert/base64.dart:83:47)
#3      new Encrypted.fromBase64 (package:encrypt/src/encrypted.dart:14:33)
#4      Encrypter.decrypt64 (package:encrypt/src/encrypter.dart:41:30)
#5      EncryptionUtil.decryptValue (package:at_client/src/util/encryption_util.dart:24:22)
#6      SelfKeyDecryption.decrypt (package:at_client/src/decryption_service/self_key_decryption.dart:35:29)
<asynchronous suspension>
#7      getAtsignData (file:///home/cconstab/Colin-snippets/ssh_control/bin/ssh_control.dart:82:17)
<asynchronous suspension>
cconstab@servalan:~/Colin-snippets/ssh_control$ 

```

**Smartphone (please complete the following information):**
 -Dart

**Additional context**
If you have ever seen `FormatException: Invalid length, must be multiple of four (at character 4)` or similar you are likely catching the 15 second keep alive on the monitor connection as well !

**Comment by cconstab** [comment]
Demo code here in the ssh_control folder

https://github.com/atsign-company/Colin-snippets

**Comment by murali-shris** [comment]
defensive fix done in at_client
https://github.com/atsign-foundation/at_client_sdk/pull/459

**Comment by sitaram-kalluri** [comment]
The root cause of the issue is Stats Notification Service send a notification in plain text and the app code is trying to decrypt the notification value.
Below are the two approaches to solve the issue:
1. Set `shouldDecrypt` method in subscribe method in notification service to true. This returns the notifications decrypted out of the box.
2. App code should have a logic to ignore the notifications with id -1.

To the second part of the bug - handling the exception, Had a chat with @VJag; This gets covered as a part [error exposure and handling](https://github.com/atsign-foundation/at_client_sdk/issues/468)

**Comment by gkc** [comment]
Per discussion on sprint planning @VJag @cconstab Once fsync is being used this will become irrelevant as statsNotifications will no longer be generated; so we probably don't need to do anything extra server-side

**Comment by cconstab** [comment]
Yup sounds good

**Comment by cconstab** [comment]
I have moved to shouldDecrypt  and tested with sshnoports code which is working as expected ... Thanks @kalluriramkumar
