### ISSUE TITLE
Add new CICD atsigns for end to end tests

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_client_sdk#447]
**Is your feature request related to a problem? Please describe.**

#446 needs to have its own atsigns for CICD to prevent any crosstalk between at_server and at_client_sdk end-end tests.

**Describe the solution you'd like**

Create new atsigns: cicd7 & cicd8

**Describe alternatives you've considered**

Do these need to be dess atsigns, or can they just run on staging (comes down to which version of secondary they should be testing against)? @kalluriramkumar please comment.

**Comment by sitaram-kalluri** [comment]
@cpswan : We need 4 atsigns. 2 atsigns running on at_secondary_server trunk branch code and another 2 atsigns running on latest canary releases.

**Comment by cpswan** [comment]
There are 4 new atsigns:

@ce2e1 host cicd1.atsign.wtf image atsigncompany/secondary:dess_cicd 
@ce2e2 host cicd2.atsign.wtf image atsigncompany/secondary:dess_cicd 
@ce2e3 host cicd1.atsign.wtf image atsigncompany/secondary:canary
@ce2e4 host cicd2.atsign.wtf image atsigncompany/secondary:canary

**Comment by gkc** [comment]
@ce2e1 host cicd1.atsign.wtf is on port 6564
@ce2e2 host cicd2.atsign.wtf is on port 6564

@ce2e3 host cicd1.atsign.wtf is on port 6565
@ce2e4 host cicd2.atsign.wtf port 6565
