### ISSUE TITLE
Generate notification id on the at_client.

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#451]
**Is your feature request related to a problem? Please describe.**
At the moment, the notification Id is generated in the cloud secondary. As a result, we have to await until  the notification Id is generated on the cloud returned.

**Describe the solution you'd like**
Generate the notification id on the at_client and make necessary changes in downstream layers to support the changes.

**Comment by gkc** [comment]
Covered by https://github.com/atsign-foundation/at_server/issues/546 - closing this one
