### ISSUE TITLE
Implement error exposure and handling

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#469]
**Is your feature request related to a problem? Please describe.**
Place holder for the implementation work for the design produced in task https://github.com/atsign-foundation/at_client_sdk/issues/468

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

- [x] Design
- [x] Implement exception chaining for get method
- [x] Implement exception chaining for put method 
- [x] QA Testing
- [x] Merge to trunk branch
- [x] Publish the changes.

**Comment by murali-shris** [comment]
New exception hierarchy. Work in progress
https://github.com/atsign-foundation/at_tools/tree/error_handling/at_commons

**Comment by sitaram-kalluri** [comment]
Completed implementation for exception chaining for AtClient get and put methods. Spent 8 SP
Following is the PR: https://github.com/atsign-foundation/at_client_sdk/pull/513

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client 3.0.26 version.
