### ISSUE TITLE
A couple issues I'm having when using atsign_authentication_helper

### ISSUE THREAD

**Issue by BermyToiga** [atsign-foundation/at_client_sdk#48]
Hard to articulate, but I'll do my best to explain.

1. After successful QR screen authentication and loading the next screen, I do not have access to the atClient Instance. I have to log out and re-authenticate with keychain in order to create polls, start monitor, or get the currentAtsign for example.

2. If the device already has an atSign in keychain that was authenticated in a different way (e.g. The beta testers that authenticated with at_client_mobile +3 version weeks before the v4 update), they can authenticate fine but when doing update or lookup, although it doesn't error, I can't get or put anything.

**Comment by Sameeraja-Bharathula** [comment]
While trying to build the android apk of takeavote, I am getting following issue. Did you encounter this issue?
BUILD FAILED in 44s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin at_contacts_flutter...

**Comment by BermyToiga** [comment]
Yeah. I'm not able to get the android version to build. I've had that problem for quite a while I'm not sure why. I've been focussing on getting it ready for iOS release and then trying to deal with the android issues

**Comment by Sameeraja-Bharathula** [comment]
1 and 2 were fixed. It is related to the app service. changes have been made and pushed to a branch called multiple_atsign_poll. This has also fixed the android build fail issue. 
Attaching the drive link for the fix scenario.
https://drive.google.com/file/d/11DKgtp6aT1niDCN38PGXWsxzbTgKbaYQ/view?usp=sharing

**Comment by BermyToiga** [comment]
Wow great thank you!  I will pull this now and test with it

**Comment by BermyToiga** [comment]
Okay, I'm glad to see that I'm finally able to use the atClientService again!
The getAtClientForAtsign() function that I had was copied from at_settings repo back when the at_client_mobile version +4 came out and all those changes were needed. I'm not sure when this needed to update to how it is now, but I'd like to know how I can make sure to be aware of things like this that need to change in the future to avoid these kinds of issues!
Thanks again!

I am running into a new issue now when I try to create a poll. It's acting similar to how issue 1 did, When I try to create a poll and send it out, it seems to send out fine, I get the typical expected response in my code:

`flutter: poll_36f8ba44-e4c8-4a42-b768-e75663284b2c
flutter: JSONPOLL: {id: 36f8ba44-e4c8-4a42-b768-e75663284b2c, topic: Misc., icon: {codePoint: 58775, fontFamily: MaterialIcons, fontPackage: null, matchTextDirection: false}, title: test poll again again, description: , options: [1, 2], sharedTo: [@colin🛠], anon: false, sharedBy: @barbara🛠, whenReleased: 2021-02-23T16:50:00.000Z, voteSubmissions: []}
flutter: [{id: 3, name: lastCommitID, value: 31}]
flutter: INFO|2021-02-23 12:45:19.489591|SyncManager|server and local is in sync
flutter: attempting put to @colin🛠
flutter: [{id: 3, name: lastCommitID, value: 32}]
flutter: INFO|2021-02-23 12:45:19.545192|SyncManager|server and local is in sync
flutter: check put to @colin🛠 ^`

However, When I try to reload the page and get my polls I get this error:

`[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Invalid or corrupted pad block
#0      PKCS7Padding.padCount 
package:pointycastle/paddings/pkcs7.dart:42
#1      PaddedBlockCipherImpl.doFinal 
package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:112
#2      PaddedBlockCipherImpl.process 
package:pointycastle/padded_block_cipher/padded_block_cipher_impl.dart:74
#3      AES.decrypt 
package:encrypt/…/algorithms/aes.dart:55
#4      Encrypter.decryptBytes 
package:encrypt/src/encrypter.dart:25
#5      Encrypter.decrypt 
package:encrypt/src/encrypter.dart:31
#6      Encrypter.decrypt64 
package:encrypt/src/encrypter.dart:41
#7      EncryptionUtil.decryptValue 
package:at_client/…/util/encryption_util.dart:22
#8      EncryptionService.decryptForSelf 
package:at_client/…/service/encryption_service.dart:223
<asynchronous suspension>
#9      AtClientImpl._get 
package:at_client/…/client/at_client_impl.dart:329
<asynch<…>`

and the person who was sent the poll gets this when trying to load it:

`flutter: sharers: [@barbara🛠]
flutter: INFO|2021-02-23 12:47:50.485354|AtLookup|auth success
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Unsupported block type for private key: 73
#0      PKCS1Encoding._decodeBlock 
package:pointycastle/asymmetric/pkcs1.dart:144
#1      PKCS1Encoding.processBlock 
package:pointycastle/asymmetric/pkcs1.dart:96
#2      RSAPrivateKey._processInBlocks 
package:crypton/…/rsa/private_key.dart:101
#3      RSAPrivateKey.decryptData 
package:crypton/…/rsa/private_key.dart:84
#4      RSAPrivateKey.decrypt 
package:crypton/…/rsa/private_key.dart:77
#5      EncryptionUtil.decryptKey 
package:at_client/…/util/encryption_util.dart:32
#6      EncryptionService.decrypt 
package:at_client/…/service/encryption_service.dart:135
<asynchronous suspension>
#7      AtClientImpl._get 
package:at_client/…/client/at_client_impl.dart:263
<asynchronous suspension>
#8      AtClientImpl.get 
package:at_client/…/client/at_client_impl.dart:341
#9      TakeAVoteService.getSharedPolls (package:takeavote/services<…>`

I have seen this "Invalid or corrupted pad block" issue for a long time now, but it didn't seem to be breaking anything until now.
