### ISSUE TITLE
getKeys gives no data with at_client 3.0.20

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#497]
**Describe the bug**
While using at_client: "3.0.20" on atmospherePro, I could not see any received files.
when looked into getAtKeys method, it was giving no data .

`atClient.getAtKeys(
              regex: 'file_transfer_'
            );`

 `var scanResult = await getSecondary().executeVerb(builder);` 

Similarly, to populate sent history we also use getAtKeys method which is working as expected.
Only difference we have is sharedBy paramater  is added.

`atClient.getAtKeys(
      regex: MixedConstants.FILE_TRANSFER_KEY,
      sharedBy: atClient.getCurrentAtSign()
    );`

**To Reproduce**
1. use atmospherePro trunk branch and update dependency
2. check if you are on at_client : "3.0.20"
3. go to received files, data should not show up.

**Expected behavior**
atClient.getAtKeys should return the atKeys matching the regex.

**Screenshots**
<img width="1098" alt="Screenshot 2022-04-28 at 7 35 15 PM" src="https://user-images.githubusercontent.com/74917871/165771886-7b52c104-86ab-456b-b876-bf784141634a.png">

**Smartphone (please complete the following information):**
 - macOS

**Were you using an @‎application when the bug was found?**
  - atmospherePro

**Additional context**
If we use the same atsign on testflight version or point to at_client: "3.0.18" it works as expected and we could see received files.

**Comment by sachins-geekyants** [comment]
Also, I noticed none of the contacts showed up.

 `atContactImpl.listContacts()` also uses getAtKeys method.

**Comment by gkc** [comment]
@srieteja please add a test to prevent regression - thanks!
