### ISSUE TITLE
Update Github and Pub.dev Readme/Overview for IoT Audience

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#507]
- [x] Review all our current Github Readme files and update relevant keywords for IoT 
- [x] Review all our current Pub.dev packages and update relevant keywords for IoT

**Comment by ksanty** [comment]
@anthonyvprakash do we have a list of keywords?  If not who will be doing the research and establishing those?

**Comment by cpswan** [comment]
IoT has been sprinkled where it made sense.
