### ISSUE TITLE
Stream of AtKey from remote secondary

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/at_client_sdk#519]
**Is your feature request related to a problem? Please describe.**

I want to update the UI of my @dude app every time I receive a new dude or `AtKey`. To achieve this I have to use the below code snippet.
```Dart
class MySyncProgressListener extends SyncProgressListener {
  @override
  void onSyncProgressEvent(SyncProgress syncProgress) async {
    if (syncProgress.syncStatus == SyncStatus.success) {
      BuildContext context = NavigationService.navKey.currentContext!;
      await context.read<DudeController>().getDudes();
    }
  }
}
```
Every time I receive a new `AtKey` sync is called but not every time sync is called I receive a new `AtKey`. This mean I'm trying to get a new `AtKey` even when there isn't a new `AtKey` in my remote secondary.

**Describe the solution you'd like**

Ideally, I would like to have access to a Stream of `AtKey` from remote secondary that I can listen to. This would make it super easy to update my UI with the help of `StreamProvider`. I should also be able to filter the `AtKey` since not all the `AtKey` will be relevant from a UI perspective. Firebase have a developer friendly way in which this is done in their [documentation](https://firebase.google.com/docs/firestore/query-data/listen#dart_1).

**Comment by xavierchanth** [comment]
Work encapsulated in: [at_tools#193](https://github.com/atsign-foundation/at_tools/issues/193)
