### ISSUE TITLE
Failed to get shared key while encrypting / decrypting message

### ISSUE THREAD

**Issue by nitesh2599** [atsign-foundation/at_client_sdk#534]
**Describe the bug**
Getting the exception `"Null" is not subtype of type 'FutureOr<String>'` while sending and receiving notifications.
We received a notification on atmosphere pro, we got the above mentioned exception while decrypting.

**To Reproduce**
Steps to reproduce the behavior (Not always reproducible):
1. Log in with `perfectbluesnowskiing` on the receiver side.
2. Send a notification to the atsign.
3. Got the above exception on decrypting.

**Expected behavior**
The notification should be decrypted without any error.

**Screenshots**
<img width="1016" alt="Screenshot 2022-05-26 at 3 20 10 PM" src="https://user-images.githubusercontent.com/74917928/170480455-80bed9e7-4704-4932-b7f7-e07ae9bbe438.png">
<img width="936" alt="Screenshot 2022-05-24 at 12 55 02 PM" src="https://user-images.githubusercontent.com/74917928/170480476-19d45cd9-1947-4e58-b392-7b92b657e833.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - `@mosphere pro`

**Additional context**
[Add any other context about the problem here.
](https://github.com/atsign-foundation/apps/issues/583)

**Comment by purnimavenkatasubbu** [comment]
I was able to replicate this issue only when the network is down. 
Steps I followed

- Switched off the network
-  I could see the error in the app
-  Sent a file from a desktop app
- Switched on the network back, I received the notification and was able to download the file.

https://user-images.githubusercontent.com/43639593/171405592-a394ed44-24c9-4c75-911c-a6d66dac5970.mp4

Note: In the desktop app, For the banamaniathenenvious atsign. There was an invalid or corrupted pad block exception.

![Screenshot from 2022-06-01 17-51-27](https://user-images.githubusercontent.com/43639593/171405837-2296a62b-91e7-4385-acd6-65df03651722.png)

**Comment by murali-shris** [comment]
@nitesh2599 did you also face "invalid or corrupted pad block" exception as reported by Purnima?

**Comment by nitesh2599** [comment]
@murali-shris No, we didn't face "invalid or corrupted pad block".

**Comment by sitaram-kalluri** [comment]
@sachins-geekyants : This issue is fixed as a part of exception chaining PR and currently the changes are available in at_client trunk branch. Please re-test and let us know if you still see the issue.

**Comment by gkc** [comment]
@sachins-geekyants can you confirm this has been fixed?

**Comment by sachins-geekyants** [comment]
@gkc I haven't experienced this issue lately, but we can keep this ticket open until a new version of atmosphere is available to test for wider users.

**Comment by sachins-geekyants** [comment]
We have deployed `@mopsherePro` 1.0.7(43), which uses `shouldDecrypt` parameter to decrypt notifications.

**Comment by sachins-geekyants** [comment]
Moving to requires validation.

**Comment by gkc** [comment]
Closing as obsolete
