### ISSUE TITLE
need for client side compaction of commit log

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#553]
**Is your feature request related to a problem? Please describe.**
* we do not have client side compaction of commit log. In apps that update log of distinct keys, commit log size may grow beyond accepted size.

**Describe the solution you'd like**
* explore options to compact on client side / alternative data structure to commit log

**Comment by VJag** [comment]
This can be moved to backlog

**Comment by murali-shris** [comment]
Initial version of draft implementation done. Addressing review comments and completing implementation, documentation and unit testing pending

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_server/pull/950
No progress in PR47 due to priority bugs

**Comment by gkc** [comment]
Will include in PR51 as Sitaram is currently doing work in the commit log area as well. Reducing to 5SP estimate

**Comment by sitaram-kalluri** [comment]
The changes are completed and the following are PRs:

at_persistence_spec: https://github.com/atsign-foundation/at_server/pull/1113
at_persistence_secondary_server: https://github.com/atsign-foundation/at_server/pull/1116
at_secondary_server: https://github.com/atsign-foundation/at_server/pull/1117

at_client: https://github.com/atsign-foundation/at_client_sdk/pull/855

**Comment by sitaram-kalluri** [comment]
Work done in PR-53:
1. Refactor commit log compaction to write functional and end2end tests. No pending work on this PR.
2. QA did testing with wavi app

**Comment by sitaram-kalluri** [comment]
The changes are merged to trunk branch

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client - v3.0.53
