### ISSUE TITLE
Discussion on breaking change in exception chaining

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#556]
At the moment, AtClientException class in defined in at_client package. During the refactoring of exception hierarchies, AtClientException class is deprecated in at_client package and moved to at_commons package.

Now the apps have both the imports:
`import at_client/at_client.dart` and
`import at_commons/at_commons.dart` because of which AtClientException fails to resolve.

`The name 'AtClientException' is defined in the libraries 'package:at_client/src/exception/at_client_exception.dart' and 'package:at_commons/src/exception/at_client_exceptions.dart (via package:at_commons/at_commons.dart)'
`

In the new release, in at_client, we have removed exporting the AtClientException class from at_client package and exported the AtClientException class from at_commons package.

So, the apps have to upgrade to the latest versions of both at_client and at_commons packages to avoid the above mentioned error. 
Upgrading only at_commons version without upgrading the at_client version causes code break.

**Comment by gkc** [comment]
@kalluriramkumar Thanks. Would this work?
* Publish at_client package and in its pubspec have it require a new minimum at_commons version
* Publish new at_commons version

**Comment by kalluriramkumar** [comment]
@gkc : Yes, that should work.

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar Thanks. Would this work?
> 
> * Publish at_client package and in its pubspec have it require a new minimum at_commons version
> * Publish new at_commons version

@gkc : Yes, this should work.

**Comment by sitaram-kalluri** [comment]
The packages are published and closing this ticket.
