### ISSUE TITLE
Need lints package to be moved to dev_dependencies and upgraded

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_client_sdk#573]
**Describe the bug**

The older version of `lints` package is blocking the latest apps to use the latest lints version. 

**To Reproduce**
1. Create a flutter/at_app project
2. Add at_client/at_client latest version and also the lints package latest version
3. Now pub get

**Expected behavior**
No Errors must be thrown.

**Were you using an @‎application when the bug was found?**
  - Buzz-2.0

**Additional context**

Logs

```
[buzz] flutter pub get
Running "flutter pub get" in buzz...                            
Because no versions of at_onboarding_flutter match >4.0.3 <5.0.0 and at_onboarding_flutter 4.0.3 depends on at_client ^3.0.15, at_onboarding_flutter ^4.0.3 requires at_client ^3.0.15.
And because at_client >=3.0.4 depends on lints ^1.0.1, at_onboarding_flutter ^4.0.3 requires lints ^1.0.1.
So, because buzz depends on both at_onboarding_flutter ^4.0.3 and lints ^2.0.0, version solving failed.
pub get failed (1; So, because buzz depends on both at_onboarding_flutter ^4.0.3 and lints ^2.0.0, version solving failed.)
exit code 1
```

**Comment by yahu1031** [comment]
This is going to be marked as a duplicate WRT https://github.com/atsign-foundation/at_widgets/issues/432. This is going to be close simultaneously with that linked issue if it resolves.

**Comment by sitaram-kalluri** [comment]
The lint version of at_client and at_client_mobile are updated to at_client - 2.0.0 and at_client_mobile - 3.2.1. Spent 2 SP in PR-42

**Comment by yahu1031** [comment]
This version has been deployed. So closing this as completed.
