### ISSUE TITLE
sync conflict resolution

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#577]
**Is your feature request related to a problem? Please describe.**
- when a key is updated both in local and remote secondary come up with a conflict resolution strategy that apps can make use of.

**Comment by murali-shris** [comment]
Below design proposed by @VJag 
// Change 1: Sync service provides a way for the app developers to register a KeyConflictResolver
// KeyConflictResolver will be used to resolve what action to take when value in cloud secondary and value in local secondary are different during a sync when the value is pulled fromt he server.
SyncService {
	void addKeyConflictResolver(KeyConflictResolver resolver);
	void removeKeyConflictResolver(KeyConflictResolver resolver);
}



// KeyConflictResolver will be used to resolve what action to take when value in cloud secondary and value in local secondary are different during a sync when the value is pulled fromt he server.
KeyConflictResolver {
	ResolutionStrategy resolve(ResolutionContext context)
}

ResolutionStrategy {
	useLocal, useCloud
}

ResolutionContext {
	
	AtKey key;
	SyncEntry localEntry;
	SyncEntry cloudEntry;
	SyncType? initialPushToServer, initialPullFromServer, pullFromServer, pushToServer;
}

SyncEntry {
	String commitID; 
	String decryptedValue;
}

**Comment by VJag** [comment]
## Conflict resolution Flowchart
```mermaid
flowchart TD
    A[Start] --> B[Sync]
    B --> C[Pull from cloud]
    C --> D{Key exists?}
    D -->|No| E[Write to local secondary]
    D -->|Yes| F{Requires decryption?}
    F --> |Yes| L[Decrypt]
    F --> |No| G[Compare Values]
    L --> G 
    G --> H{Is there a conflict?}
    H -->|No| J[Inform sync progress]
    H -->|Yes| I[Resolve conflict]
    E --> J
    I --> J
    J --> K[End]
```

**Comment by VJag** [comment]
## Conflict resolution class diagram
```mermaid

classDiagram
    SyncService ..> KeyConflictResolver : Dependency
    KeyConflictResolver ..> ResolutionStrategy : Dependency
    KeyConflictResolver ..> ResolutionContext : Dependency
    ResolutionContext ..> SyncEntry : Dependency
    ResolutionContext ..> SyncType : Dependency

    class SyncService {
        void setKeyConflictResolver(KeyConflictResolver resolver); 
        void removeKeyConflictResolver(KeyConflictResolver resolver);

    }
    class KeyConflictResolver {
        ResolutionStrategy resolve(ResolutionContext context)
    }

    class ResolutionStrategy {
        enum useLocal, useRemote
    }

    class SyncType {
        enum initialPushToRemote, initialPullFromRemote, pullFromRemote, pushToRemote
    }

    class ResolutionContext {

        AtKey key
        SyncEntry localEntry
        SyncEntry remoteEntry
        SyncType syncType
    }

    class SyncEntry {
           String commitID; 
           String decryptedValue;
    }

 ```

**Comment by gkc** [comment]
Nice diagrams!

**Comment by murali-shris** [comment]
Sample app code for resolution

syncService.setKeyConflictResolver(MyConflictResolver());

```
MyConflictResolver extends KeyConflictResolver {
	
	ResolutionStrategy resolve(ResolutionContext context) {

			if(context.key.toString().matches(RegEx('xyz')) {
				return ResolutionStrategy.useLocal;
			}

			if (context.localEntry.decryptedValue.equals('NO')) {
				return ResolutionStrategy.useRemote;
			}

			if (context.syncType.initialPushToRemote) {
				return ResolutionStrategy.useLocal;
			}

			if (context.localEntry.decryptedValue > context.cloudEntry.decryptedValue) {
				return ResolutionStrategy.useRemote;
			}

			return ResolutionStrategy.useRemote;
	}

}
```

**Comment by murali-shris** [comment]
latest code changes 
https://github.com/atsign-foundation/at_client_sdk/tree/sync_conflict_resolution
Discussed with Gary and Jagan.. Decision was made not to complicate the conflict resolution..Just determine conflict exists or not and then add conflict information to KeyInfo object and pass to sync progress call back.

**Comment by murali-shris** [comment]
latest changes in a new branch
https://github.com/atsign-foundation/at_client_sdk/commit/7093cc9a2e9dbbae4014084bb456be719288d0dd

**Comment by murali-shris** [comment]
burnt 8SP in PR 40. 
Pending task - complete unit tests, PR review and publish at client

**Comment by murali-shris** [comment]
Sample listener example that app developers can refer to
```
class MySyncProgressListener1 extends SyncProgressListener {
  @override
  void onSyncProgressEvent(SyncProgress syncProgress) {
    for (var keyInfo in syncProgress.keyInfoList!) {
      print(
          'Key synced: ${keyInfo.key} sync direction: ${keyInfo.syncDirection}');
      final conflictInfo = keyInfo.conflictInfo;
      if (conflictInfo != null) {
        print('conflict exists for key: ${keyInfo.key}');
        print(
            'local value: ${conflictInfo.localValue} remote value: ${conflictInfo.remoteValue}');
      }
    }
  }
}
```

**Comment by murali-shris** [comment]
changes published. at_client v3.0.30

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_client_sdk/issues/601#issuecomment-1192223344

**Comment by murali-shris** [comment]
doc task https://github.com/atsign-foundation/at_client_sdk/issues/601
