### ISSUE TITLE
Documentation - missing comments for Metadata parameters

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#580]
**Is your feature request related to a problem? Please describe.**
Comments are missing for `Metadata` parameters like `ttr`, `ttl`, etc.

**Describe the solution you'd like**
Can we add comments like what this parameter does and also the unit it accepts the data in.

**Comment by sitaram-kalluri** [comment]
The changes are pushed and merged to trunk branch in the following [PR-217](https://github.com/atsign-foundation/at_tools/pull/217)

**Comment by sitaram-kalluri** [comment]
The changes are published the at_commons 3.0.22. Hence closing the issue.
