### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_client_sdk#586]
**Describe the bug**
On developing apps in android using the latest flutter template, I got this issue mentioned below.

```
[+114548 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[        ] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
[        ] The following dependencies do not satisfy the required version:
[        ] project ':flutter_keychain' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21
[        ] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[        ] > Run with --info or --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 54s
```
This looks like the `flutter_keychain` kotlin version doesn't match with the app kotlin version.

I have tried with `1.3.40`, `1.5.21`, `1.6.10` kotlin versions in `android/app/build.gradle`. But nothing works.

**To Reproduce**
1. Create a flutter template using `flutter create my_app`
2. Add `at_client_mobile: ^3.1.18` to the app.
3. Utilize any of the functions/methods from `at_client_mobile`.
4. Try running the app in debugging on an android device.

**Expected behavior**
Must build an app without any error.

**Smartphone (please complete the following information):**
 - Device: Redmi 8
 - OS: Android 10
 - Version: MIUI 12

**Were you using an @‎application when the bug was found?**
  - @‎buzz

**Additional context**
Here are the logs https://cdn.sourceb.in/bins/wwGtrAOuel/0

**Comment by yahu1031** [comment]
This will come under a blocker. There is no other go other than changing the kotlin version of the `flutter_keychain` package.

**Comment by yahu1031** [comment]
There was a fix coming up with [remove_flutter_keychain](https://github.com/atsign-foundation/at_client_sdk/tree/remove_flutter_keychain) branch.

**Comment by sachins-geekyants** [comment]
@yahu1031 are you facing the same issue while running wavi or atmopsherePro app ?

**Comment by yahu1031** [comment]
Nope @sachins-geekyants, We don't see this issue anymore with the latest releases. Closing this as completed. Please reopen if you find this issue anywhere.
