### ISSUE TITLE
at_onboarding widget has version compatibility issues with kotlin version and flutter keychain.

### ISSUE THREAD

**Issue by S-Patel25** [atsign-foundation/at_client_sdk#587]
**Describe the bug**

I am trying to use the at_onboarding widget for an app in development, and whenever I try to run the code, I get an error saying ``android gradle`` version only supports ``kotlin version 1.3.40+`` despite the fact that all versions are up-to-date.

**To Reproduce**
1. First I install at_onboarding, at client in my flutter app.
2. Then I write the code for the onboarding widget.
3. And then I run the code, and get the error that the android plugin only support kotlin 1.3.40+.

**Expected behavior**

Code should run without any error, and users should be able to onboard through AtSign.

**Screenshots**

``The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
 The following dependencies do not satisfy the required version:
 project ':flutter_keychain' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21``
 * Try:
 > Run with --stacktrace option to get the stack trace.
 > Run with --info or --debug option to get more log output.
 > Run with --scan to get full insights.
 * Get more help at https://help.gradle.org``

**Smartphone (please complete the following information):**
 - Device: Pixel 4 (Used Android Emulator)
 - OS: Android 12

**Were you using an @‎application when the bug was found?**
No, just the onboarding widget.

**Comment by yahu1031** [comment]
Similar/duplicate of https://github.com/atsign-foundation/at_client_sdk/issues/586

**Comment by S-Patel25** [comment]
issue is related to the buzz issue as i have same problem with onboarding widget compatibility and that it wont run on android devices. The only packages I used were at_client and at_onboarding, and only when I tried implementing the onboarding widget did it give me the version compatibility errors.

**Comment by yahu1031** [comment]
When I dig deeper, `at_onboarding_flutter` has `at_client_mobile` utilisation in it. And as the error says, `flutter_keychain` was used in `at_client_mobile`. So the packages which have `at_client_mobile` dependency, it throw this error and it will reflect as the package error. So as I already have raised #586 which is related to it, I marked this as a duplicate.

**Comment by S-Patel25** [comment]
#586 is similar to the error I am having, so we can close this one.
