### ISSUE TITLE
Sync() is trying to sync cached keys

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#593]
**Describe the bug**
Cached keys are being tried to sync.

**To Reproduce**
1. Run the e2e tests in the client

**Expected behavior**
Cached keys should not be synced

**Logs** 
SEVERE|2022-07-08 08:07:40.614293|SyncService|update/delete for key cached:@ce2e4:phone2be257ab-07b4-412a-b5c4-a0e65df94368.wavi@ce2e1 failed. Error code AT0003 error message Invalid syntax 
  
  SEVERE|2022-07-08 08:07:40.614600|SyncService|update/delete for key cached:@ce2e4:phone6b70a796-841a-46f1-b85e-057fe1d5990c.wavi@ce2e1 failed. Error code AT0003 error message Invalid syntax 

**Screenshots**
For complete logs [Error logs](https://github.com/atsign-foundation/at_client_sdk/runs/7247807864?check_suite_focus=true)

**Comment by sitaram-kalluri** [comment]
The issue is fixed in [PR-603](https://github.com/atsign-foundation/at_client_sdk/pull/603)

**Comment by purnimavenkatasubbu** [comment]
Issue has been fixed.
