### ISSUE TITLE
Refrain from syncing the stats notification id to cloud storage

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#596]
**Is your feature request related to a problem? Please describe.**
The stats notification id gets sync'ed to the cloud secondary. Enhance the code to prevent the stats notification id being sync'ed to cloud secondary.

**Describe alternatives you've considered**

**Additional context**

**Comment by purnimavenkatasubbu** [comment]
Failing tests needs to be fixed.

**Comment by purnimavenkatasubbu** [comment]
PR merged to trunk #619
