### ISSUE TITLE
Fix sync conflict bug

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#604]
**Describe the bug**
 When resolving the sync conflict, the following keys result in exception.
1. Public key that holds encryption public key of other atsign - `public.bob@alice`
2. Self key that holds the shared key. - `shared_key.bob@alice`
3. The cached keys

**Expected behavior**
Sync conflict should not result in exception.

**Comment by kalluriramkumar** [comment]
Pulled [PR-602](https://github.com/atsign-foundation/at_client_sdk/pull/602) changes into this PR since e2e tests are failing.
