### ISSUE TITLE
Unable to sync for the first time using AtClient in atTalk

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#609]
**Describe the bug**
Using atTalk and a new atSign the atSign synchs within a few seconds but when using atColin the process never finishes and the hive database is not getting larger although the synch process is still not completed.

**To Reproduce**
1. First get athe atTalk code and then use an new atSign 
2. Evething works as expected
3. And then use atColin or another atSign that has more data (not sure as of yet that is the problem)
4. Notice that the synch never completes

**Expected behavior**
Initial Sync should work and be quick!

**Screenshots**
Example using atColin

```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@colin" -t "@iot_device02"
Synching your data............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

I put some defensive code in place to catch any errors you can do the same with the -v and there seem to be some good clues

```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@colin" -t "@iot_device02" -v
INFO|2022-07-14 19:48:12.548543|HiveBase|commit_log_b5b68476c4819ec05818424067ac465c1350c8adb7d376412b8eb638e2a3e413 initialized successfully 

INFO|2022-07-14 19:48:12.648086|HiveBase|b5b68476c4819ec05818424067ac465c1350c8adb7d376412b8eb638e2a3e413 initialized successfully 

INFO|2022-07-14 19:48:14.567882|Monitor|monitor started for @colin with last notification time: null 

INFO|2022-07-14 19:48:15.793996|AtLookup|auth success 

INFO|2022-07-14 19:48:15.819612| atTalk |Waiting for initial sync 

Synching your data.............INFO|2022-07-14 19:48:21.859663|AtLookup|auth success 

INFO|2022-07-14 19:48:21.970638|SyncService|Returning the serverCommitId 427793 

INFO|2022-07-14 19:48:22.108674|SyncService|Returning the serverCommitId 427793 

......................SEVERE|2022-07-14 19:48:33.105447|AtLookup|Exception in sending to server, Exception: No response after 10000 millis from remote secondary 

SEVERE|2022-07-14 19:48:33.105567|AtLookup|Error in remote verb execution Exception: No response after 10000 millis from remote secondary 

SEVERE|2022-07-14 19:48:33.106902|SyncService|Exception in sync 5d1154f3-f606-4e03-92ac-daab4b517cde. Reason Exception: Exception: No response after 10000 millis from remote secondary 

......................SEVERE|2022-07-14 19:48:44.189660|AtLookup|Exception in sending to server, Exception: No response after 10000 millis from remote secondary 

SEVERE|2022-07-14 19:48:44.189763|AtLookup|Error in remote verb execution Exception: No response after 10000 millis from remote secondary 

SEVERE|2022-07-14 19:48:44.189881|SyncUtil|Exception while getting latest server commit id: Exception: Exception: No response after 10000 millis from remote secondary 

SEVERE|2022-07-14 19:48:44.189954|SyncService|Exception in sync 5d1154f3-f606-4e03-92ac-daab4b517cde. Reason Exception: Unable to fetch latest server commit id: Exception: Exception: No response after 10000 millis from remote secondary 

...................SEVERE|2022-07-14 19:48:53.615927|AtLookup|Exception in sending to server, ErrorCode: AT0014 - Exception: Unexpected response found 

SEVERE|2022-07-14 19:48:53.616029|AtLookup|Error in remote verb execution ErrorCode: AT0014 - Exception: Unexpected response found 

SEVERE|2022-07-14 19:48:53.616141|SyncUtil|Exception while getting latest server commit id: Exception: ErrorCode: AT0014 - Exception: Unexpected response found 

SEVERE|2022-07-14 19:48:53.616204|SyncService|Exception in sync 5d1154f3-f606-4e03-92ac-daab4b517cde. Reason Exception: Unable to fetch latest server commit id: Exception: ErrorCode: AT0014 - Exception: Unexpected response found 

SEVERE|2022-07-14 19:48:53.656971|JsonDecode|Failed to decode jsonString : [{"id":"3","name":"lastCommitID","value":"427793"}]
@colin@[{"id":"3","name":"lastCommitID","value":"427793"}] Error : FormatException: Unexpected character (at line 2, character 1)
@colin@[{"id":"3","name":"lastCommitID","value":"427793"}]
^
 

...INFO|2022-07-14 19:48:55.058353|SyncService|Returning the serverCommitId 427793 

INFO|2022-07-14 19:48:55.159795|SyncService|Returning the serverCommitId 427793 

...........................................................................................................................................................................................................................................................
```

example using newer atSign shows a clean start
 
```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@iot_device01" -t "@iot_device02"
Synching your data..............................
@iot_device01:
```

**Were you using an @‎application when the bug was found?**
  -atTalk (use the `testing-await` branch as that is what I used to test too

**Additional context**

**Comment by cconstab** [comment]
I think to figure this one out it will be useful to have the TLS decode options in place so we can see what is happening on the wire

**Comment by murali-shris** [comment]
@cconstab I tried replicating the issue with at_client v3.0.29..I could see errors related to syncing cached keys. We fixed this issue in v3.0.30. 
With v3.0.30, sync completed in approx 4 mins
INFO|2022-07-19 15:23:17.669417|SyncService|Returning the serverCommitId 429392 

.INFO|2022-07-19 15:23:18.013272|SyncService|Returning the serverCommitId 429392 

..................................................................................................................................................................................................................................................................................................................................................................................................................................................................INFO|2022-07-19 15:27:03.846439|SyncService|Inside syncComplete  SyncRequestSource.app  : Closure: (dynamic) => void 

INFO|2022-07-19 15:27:03.846562|SyncService|Sending result to onDone callback 

INFO|2022-07-19 15:27:03.847160| atTalk |syncResult.syncStatus: SyncStatus.success 

INFO|2022-07-19 15:27:03.847340| atTalk |syncResult.lastSyncedOn 2022-07-19 09:57:03.846186Z

**Comment by cconstab** [comment]
very nice and confirmed with my client too THANKS

```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@colin" -t "@iot_device02"
Syncing your data............................................................................................................................................................................................................................................................................................................................................................................................................
@colin: 
```

**Comment by cconstab** [comment]
@murali-shris I am wondering if it might be an idea/possible to provide a number of commits to go so instead of dots I could provide a countdown to 0 commits left as part of the sync ?

**Comment by gkc** [comment]
Absolute number not possible without making changes to get a count from server back to the client 

An **indicator** of how far along you are is doable just on client side since we know what our starting local commit id is, and what the server commit id is. The difference between those two isn't necessarily the actual number of entries to sync though (because regexes)

**Comment by gkc** [comment]
We can close this as fixed. @cconstab I will file a feature request re the sync progress per your comment above

**Comment by gkc** [comment]
Filed #617
