### ISSUE TITLE
Add tests to catch sync issues

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#627]
**Describe the bug**
No tests caught the sync issue which is fixed by #625 

**Expected behavior**
We need unit tests which cover this scenario.

**Additional context**
sshnoports issue encountered by Colin (**TODO**: when it is created, link to the ticket from here)

**Comment by murali-shris** [comment]
Purnima tried to replicated exception scenario for sync failure. Have to explore on alternate possibilities
