### ISSUE TITLE
at client mobile 3.2.1 breakage

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_client_sdk#632]
**Describe the bug**
When I call `KeyChainManager.getInstance().getAtsignsWithStatus()`, I get this invalid format exception.

**To Reproduce**
Just call `KeyChainManager.getInstance().getAtsignsWithStatus()`.

**Expected behavior**
It must either return empty array or some array data.

**Screenshots**
![Screenshot 2022-08-01 at 11 43 18 PM](https://user-images.githubusercontent.com/35523357/182214378-d56d9c86-d40d-41fa-a7fe-9aa4f82e7e15.png)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS15.5

**Were you using an @‎application when the bug was found?**
  - @‎buzz

**Additional context**
I have deep dived to the error and I found [`final json = jsonDecode(value ?? '');`](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/at_client_mobile/lib/src/keychain_manager.dart#L34). So `jsonDecode('')` cannot format the data. It actually throws 
```
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
```
Exception.

So the work around can be `final json = jsonDecode(value ?? '{}');`.

**Comment by murali-shris** [comment]
Issue can be closed once at client is published

**Comment by purnimavenkatasubbu** [comment]
Verified with the trunk branch of at_client_mobile. I don't see the above exceptions anymore. Attaching the app logs for reference.
[client_mobile_trunk_logs.txt](https://github.com/atsign-foundation/at_client_sdk/files/9292990/client_mobile_trunk_logs.txt)
[buzz_clientMobile_trunk_logs.txt](https://github.com/atsign-foundation/at_client_sdk/files/9292993/buzz_clientMobile_trunk_logs.txt)

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_client_sdk/pull/647
Publishing of at_client_mobile is blocked by end to end test failures

**Comment by gkc** [comment]
#647 is unblocked, has been merged to trunk, is ready for the package to be published

**Comment by sitaram-kalluri** [comment]
The at_client_mobile v3.2.2 is published. Marking this issue as fixed.

**Comment by murali-shris** [comment]
at client mobile 3.2.2 published.
@cconstab please re-test with 3.2.2 and let us know whether onboarding is successful.
