### ISSUE TITLE
authenticate returns true for invalid atKeys file

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#640]
**Describe the bug**
If we reset an atSign and activate it again we will have a new atKeys file and old atkeys file will become invalid.
`AtClientService.authenticate` returns **true** for old atkeys file as well.

**To Reproduce**
1. activate an atSign and get the atKeys file.
2. reset the atSign.
3. activate again and get new atKeys file.
4. If we upload old atKeys file to authenticate it returns `true`.

**Expected behavior**
`AtClientService.authenticate` should return false for invalid atKeys.

**Smartphone (please complete the following information):**
 - macOS
 
**Were you using an @‎application when the bug was found?**
  - atmospherePro

**Comment by cconstab** [comment]
Possible that the old keys are being synched from an old client ?

**Comment by sitaram-kalluri** [comment]
Fixed the issue and the changes are available in https://github.com/atsign-foundation/at_client_sdk/pull/666. Request the apps team/QA team to test the changes. The changes are available in `fix_auth_issue` in at_client_sdk repo.

**Comment by sachins-geekyants** [comment]
@kalluriramkumar  With the shared at_client branch, the issue is not reproducibile.

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar With the shared at_client branch, the issue is not reproducibile.

@sachins-geekyants : Great, Can you please confirm the regression tests are also covered?

**Comment by ayushkumarrojha** [comment]
@sachins-geekyants 

This issue is not reproducible with atmosphere pro invalid-atkey branch on the below configurations:

**Device Details:**
Device: iPhone XR
OS: iOS 15.6

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client_mobile : 3.2.5
