### ISSUE TITLE
malformed key exception in buzz

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#655]
**Describe the bug**
flutter: SEVERE|2022-08-13 13:29:52.260256|LoadingScreen|Failed to load data : Exception: _latestNotificationIdv2.buzz is not well-formed key

**To Reproduce**
- point buzz app to at_client trunk branch
- onboard with any atsign
**Expected behavior**
- no exception during onboard

**Comment by gkc** [comment]
@murali-shris Does the test in stats_notification_sync_test.dart make any sense to you? I don't really understand what it's trying to do, and in any event I don't believe we are syncing the notification ID any more (see `SyncUtil.shouldSync`)

**Comment by gkc** [comment]
From `NotificationServiceImpl._getLastNotificationTime()`
```
    var lastNotificationKeyStr =
        '$notificationIdKey.${_atClient.getPreferences()!.namespace}${_atClient.getCurrentAtSign()}';
    var atKey = AtKey.fromString(lastNotificationKeyStr);
```
`AtKey.fromString` is the only place that generates a "is not well-formed key" message

The error is valid - it is indeed not a well-formed key - but it shouldn't be happening, because currentAtSign() should not be null.

It can only be happening because, for some reason, current atSign is not set when `_getLastNotificationTime()` is being called (which can be during the initial startMonitor, or a restart of the monitor for example)

@yahu1031 can you verify please what the currentAtSign is set to? I've pushed a branch in at_client_sdk called `logCurrentAtSignAtVariousTimes` which will log the current atSign at various times

**Comment by gkc** [comment]
@yahu1031 @murali-shris where is the Buzz source code?

**Comment by yahu1031** [comment]
Lemme update the code with new branch @gkc

**Comment by gkc** [comment]
Can you point me at the source code please @yahu1031 ?

**Comment by murali-shris** [comment]
> shouldSync

it triggers a sync and asserts that notificationKey is not synced. But I think the check should happen in the onDone call back instead of main()

**Comment by murali-shris** [comment]
> @murali-shris Does the test in stats_notification_sync_test.dart make any sense to you? I don't really understand what it's trying to do, and in any event I don't believe we are syncing the notification ID any more (see `SyncUtil.shouldSync`)

it triggers a sync and asserts that notificationKey is not synced. But I think the getAtKey and assert should happen in the onDone call back instead of main()

**Comment by yahu1031** [comment]
@gkc When I call 
```dart
await ServiceInstances.atClientManager
    .setCurrentAtSign(
        context.read<UserData>().currentAtSign,
        BuzzEnv.appNamespace,
        context.read<UserData>().atOnboardingPreference);
```
in the app, I get this exception
<img width="641" alt="Screenshot 2022-08-14 at 1 15 51 PM" src="https://user-images.githubusercontent.com/35523357/184527426-8c794d84-5d7d-4a6f-9016-e78741e0dc04.png">

Related code is [here](https://github.com/ramtulluri/contacts-app/tree/atbuzz-2.0)

Logs:
```
flutter: SEVERE|2022-08-14 13:17:02.714438|LoadingScreen|Failed to load data : Exception: _latestNotificationIdv2.buzz is not well-formed key
flutter: WARNING|2022-08-14 13:17:03.036799|Monitor|Heartbeat response not received within expected duration. Heartbeat was sent at 1660463024195, it is now 1660463223036, last heartbeat response was received at 0. Will close connection, set status stopped, call retryCallback
flutter: INFO|2022-08-14 13:17:03.040664|Monitor|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback
```

**Comment by yahu1031** [comment]
This doesn't happen all the time IDK why.

**Comment by gkc** [comment]
Is context.read() async?

**Comment by yahu1031** [comment]
Nope @gkc it is not. And also there is no way of missing awaits. Cause my lints are a little strict. So no awaits will be missing.

Thanks.

**Comment by gkc** [comment]
👍

Well for whatever reason, the problem seems to be that
> context.read<UserData>().currentAtSign

is returning empty string

**Comment by yahu1031** [comment]
Thanks @gkc for the help and guidance. I fixed the issue and it is from the app as you mentioned.

**Comment by yahu1031** [comment]
Closing the issue as fixed from the app side.
