### ISSUE TITLE
setCurrentAtSign allows empty string

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#657]
**Describe the bug**
AtClientManager.setCurrentAtSign allows empty string argument for atSign. This results, later, in exceptions which are not obvious to diagnose. 

**Expected behavior**
AtClientManager.setCurrentAtSign should immediately reject malformed atSign arguments with an exception 

**Additional context**
See also https://github.com/atsign-foundation/at_client_sdk/issues/655

**Comment by purnimavenkatasubbu** [comment]
PR #671 merged to trunk.

**Comment by gkc** [comment]
Thanks @purnimavenkatasubbu
