### ISSUE TITLE
Receiving multiple notifications for a single notify

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#661]
**Describe the bug**
On running atmospherePro from trunk branch, when we receive any file notification, we get multiple callbacks for the same data.

**To Reproduce**
1. run atmospsherePro trunk branch and onboard with any atSign(`@a`).
2. send file to `@a`
3. notificationcallback gets triggered twice and received items shows duplicate data.

**Expected behavior**
notificationcallback should get triggered only once.

**Screenshots**
<img width="1110" alt="Screenshot 2022-08-18 at 4 46 56 PM" src="https://user-images.githubusercontent.com/74917871/185382373-a593d86c-c1b1-4e86-a528-c49a0d6c3bb3.png">

**Smartphone (please complete the following information):**
 - macOS
 
**Were you using an @‎application when the bug was found?**
  - atmospherePro

**Comment by sachins-geekyants** [comment]
start monitor was getting called multiple times, whenever sync progress was happening. This created multiple listeners for the same regex thus we were receiving multiple notifications.

**Comment by sitaram-kalluri** [comment]
The root cause of the issue is the NotificationService is being subscribed for multiple times and hence the same notification is being delivered. Spent 5 SP on this.

**Comment by purnimavenkatasubbu** [comment]
Tested atMosphere_pro app, Now the notification is being received only once.

response => AtNotification{id: 6fab06b5-9730-489c-a6cb-5fc6ee693e7a, key: @judicialabseiling:file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6.mospherepro@jittery5justfriends, from: @jittery5justfriends, to: @judicialabseiling, epochMillis: 1662363077285, value: {"transferId":"file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6","fileEncryptionKey":"72/H3SQZalzffS92hNrgeMvpgRNuzsThoocWi9ZLWBg=","fileUrl":"https://ck6agzxiog6kmb.atsign.com/archive/file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6/zip","sharedWith":"@judicialabseiling","sharedStatus":null,"fileStatus":[{"fileName":"IMG-20220213-WA0110.jpg","isUploaded":true,"size":436646,"error":null}],"date":"2022-09-05 07:31:12.793691Z","error":null,"notes":null}, operation: update}
