### ISSUE TITLE
NotificationService.subscribe fails to return existing listener on same regex

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#684]
**Describe the bug**
When trying to reproduce the following issue: https://github.com/atsign-foundation/at_client_sdk/issues/661, Found that the notification service-> subscribe method fails to return the existing listener when already present. Instead creates a new StreamController.

The root cause of the issue is we are check on String (regex) instead of comparing on the NotificationConfig object. Below is the code snippet.

```dart
if (_streamListeners.containsKey(regex)) {
```

Fix:
Modify the streamListeners from Map to HashMap and overrides the equal and hashcode methods to compare the NotificationConfig Object.

**Comment by sitaram-kalluri** [comment]
Assigning 0SP because of the effort of this is accounted in the following git issue: https://github.com/atsign-foundation/at_client_sdk/issues/661

**Comment by purnimavenkatasubbu** [comment]
Tested atMosphere_pro app with the "fix_multiple_notification_issue", Now the notification is being received only once.

response => AtNotification{id: 6fab06b5-9730-489c-a6cb-5fc6ee693e7a, key: @judicialabseiling:file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6.mospherepro@jittery5justfriends, from: @jittery5justfriends, to: @judicialabseiling, epochMillis: 1662363077285, value: {"transferId":"file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6","fileEncryptionKey":"72/H3SQZalzffS92hNrgeMvpgRNuzsThoocWi9ZLWBg=","fileUrl":"[https://ck6agzxiog6kmb.atsign.com/archive/file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6/zip","sharedWith":"@judicialabseiling","sharedStatus":null,"fileStatus":[{"fileName":"IMG-20220213-WA0110.jpg","isUploaded":true,"size":436646,"error":null}],"date":"2022-09-05](https://ck6agzxiog6kmb.atsign.com/archive/file_transfer_ac11698b-45e7-421c-8bd5-d19b66f839e6/zip%22,%22sharedWith%22:%22@judicialabseiling%22,%22sharedStatus%22:null,%22fileStatus%22:%5B%7B%22fileName%22:%22IMG-20220213-WA0110.jpg%22,%22isUploaded%22:true,%22size%22:436646,%22error%22:null%7D%5D,%22date%22:%222022-09-05) 07:31:12.793691Z","error":null,"notes":null}, operation: update}

2nd time

I/flutter ( 8039): response => AtNotification{id: 13369f8d-98ed-4ad4-9ed7-96050305d7a9, key: @judicialabseiling:file_transfer_210a2955-54e1-4b9e-9706-f8ed7126da9b.mospherepro@27salty, from: @27salty, to: @judicialabseiling, epochMillis: 1662363962828, value: {"transferId":"file_transfer_210a2955-54e1-4b9e-9706-f8ed7126da9b","fileEncryptionKey":"5S2XKeweKxuViJX1Nl9AZJjRb7NZd9iQ8CqQNW65ys0=","fileUrl":"[https://ck6agzxiog6kmb.atsign.com/archive/file_transfer_210a2955-54e1-4b9e-9706-f8ed7126da9b/zip","sharedWith":"@judicialabseiling","sharedStatus":null,"fileStatus":[{"fileName":"20191227_144152.jpg","isUploaded":true,"size":3120893,"error":null}],"date":"2022-09-05](https://ck6agzxiog6kmb.atsign.com/archive/file_transfer_210a2955-54e1-4b9e-9706-f8ed7126da9b/zip%22,%22sharedWith%22:%22@judicialabseiling%22,%22sharedStatus%22:null,%22fileStatus%22:%5B%7B%22fileName%22:%2220191227_144152.jpg%22,%22isUploaded%22:true,%22size%22:3120893,%22error%22:null%7D%5D,%22date%22:%222022-09-05) 07:45:59.369107Z","error":null,"notes":"lotus with buddha"}, operation: update}
