### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#685]
[Event](https://hacktoberfest.com/) dates: 9/26/22 - 10/27/22

- [x] Decide on Repos that we will open up for Hacktoberfest 2022
- [x] New Labels / Reuse Labels from 2021
- [x] Assign tickets for individual owners to create new issues and apply the corresponding labels
- [ ] Can we have a goal of opening up about 100 tickets?

**Comment by ksanty** [comment]
@anthonyvprakash happy to go into the labels repo and update last years labels with current.  They look pretty generic.  Have a look - https://github.com/atsign-company/labels/labels?page=1&sort=name-asc.

**Comment by cpswan** [comment]
I've added the `hacktoberfest` topic to all of the repos we feature on our GitHub org(s) home page.

Labels are already in place from last year.

**Comment by cpswan** [comment]
Hacktoberfest is now underway, and we've seen considerable traffic relating to it.

@anthonyvprakash is the aim to have 100 across the month, as we didn't have that many at the start?

**Comment by anthonyvprakash** [comment]
@cpswan - Yes, that was at least a target for us to shoot for so that we could build on that year over year.

**Comment by cpswan** [comment]
Moving to PR48, which will take us through to almost the end of Oct (and Hacktoberfest)

**Comment by cpswan** [comment]
Closing, as today's the last day of Hacktoberfest.
