### ISSUE TITLE
Dev Site Pending Documentation

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#686]
**Context** : The new docs site https://docs.atsign.com still has a lot of outdated content. The documentation needs to be refreshed and made up to date.

We need the following to happen :
- [ ] @XavierChanth @JeremyTubongbanua  and @TylerTrott to tell the Engg and App teams on what sections need content
- [ ] @XavierChanth @JeremyTubongbanua  and @TylerTrott to create individual tickets for places that need documentation, diagram and examples
- [x] Remove auto generated links on "Get Started" and model it the main landing page of the docs site  - @TylerTrott 
- [x] https://docs.atsign.com/start/flutter/ - Step 2 : Remove the redundant text - @TylerTrott 
- [ ] https://docs.atsign.com/start/iot/ - @cpswan  and @thenobleone14 to review the content 
- [x] https://docs.atsign.com/start/other/ - Needs to move under "Contribute" - @XavierChanth 
- [x] Reorganize "Contribute" - @XavierChanth 
- [ ] atmosphere Pro Codelab to be completed - @sachins-geekyants & @nitesh2599 
- [ ] https://docs.atsign.com/sdk/java/private-hidden-key/ - To be completed and published - @JeremyTubongbanua

Flutter SDK content @purnimavenkatasubbu :
- (Eventual goal) Achieve 100% coverage of the Flutter SDK (Determine the missing content)
- [x] AtClientManager - discuss notification service and sync service before stating how to fetch it using AtClientManager
- [x] Key Basics - Remove "in atProtocol" from subheading
- [x] CRUD operations - move this section to beginning of the page
- [x] Root Server - Second diagram can be moved to secondary server

Misc:
- [ ] sshnp documentation/codelab update (Pi) @TylerTrott 

Completed:
- [x] Add icons on the landing page for the docs site - @XavierChanth 
- [x] https://docs.atsign.com/start/java/ - Windows/Linux compatibility fix - @JeremyTubongbanua 
- [x] https://docs.atsign.com/start/java/ - Fix formatting(indentation)/Headers - @JeremyTubongbanua 
- [x] https://docs.atsign.com/start/iot/ - Change IoT Devices to IoT - @JeremyTubongbanua 
- [x] https://docs.atsign.com/start/iot/ - remove description of atPlatform - @JeremyTubongbanua 
- [x] https://docs.atsign.com/start/iot/ - Bump up header font for "IoT Architecture" @JeremyTubongbanua 
- [x] https://docs.atsign.com/sdk/java/private-hidden-key/ - Should be set to 'draft' - @JeremyTubongbanua 
- [x] Add YouTube videos for the reference section - @JeremyTubongbanua 
- [x] Change discord urls to https://discord.atsign.com - @JeremyTubongbanua

**Comment by murali-shris** [comment]
@XavierChanth @TylerTrott 
I documented few minor changes required on at client sdk and server documentation.
https://docs.google.com/document/d/1DGj49jVsAqr4gS5wN6HlcEyWT9M-tHEF--MsW6_hyjo/edit
If you are fine with the changes, I can request @purnimavenkatasubbu to work on the changes

**Comment by purnimavenkatasubbu** [comment]
Raised a [PR](https://github.com/atsign-foundation/docs.atsign.com/pull/154) for the following changes.

- AtClientManager - discuss notification service and sync service before stating how to fetch it using AtClientManager
- Key Basics - Remove "in atProtocol" from subheading
- CRUD operations - move this section to beginning of the page
- Root Server - The second diagram can be moved to secondary server

**Comment by xavierchanth** [comment]
Backlogging this for the next 2 sprints @anthonyvprakash @cpswan @TylerTrott , we can reassess after Hacktoberfest.
