### ISSUE TITLE
atClientPreference in at_client_service.dart includes the atSign private key as a public member

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/at_client_sdk#687]
**Describe the bug**

In the at_client_service.dart source code, the atClientPreference in at_client_service.dart includes the atSign private key as a public member. I cannot think of any need for the private key to be accessible from the preference object and am suggesting that it be private or removed.

**To Reproduce**
1. Create an instance ```AtClientManager atClientManager = AtClientManager.getInstance(); ``` 
2. get the private key from the atClient ```atatClientManager.atClient.getPreferences()?.privateKey; ```

**Expected behavior**
The private key should likely not be accessible from the preferences object.

**Additional context**

**Comment by ksanty** [comment]
Move to high priority after arch discussion

**Comment by murali-shris** [comment]
Spent 8SP in this sprint. 
https://github.com/atsign-foundation/at_client_sdk/pull/698
When app or client is init for the first time, we have to read the private key from keychain and pass it to at_client_impl create. Have to discuss in architecture call whether passing private key to at client impl create is an acceptable approach.

**Comment by gkc** [comment]
Was this discussed, and what was the conclusion?

**Comment by murali-shris** [comment]
> Was this discussed, and what was the conclusion?

not yet Gary.Arch call discussion pending.

**Comment by murali-shris** [comment]
discussion in architecture call.
* persisting private key from keychain to keystore should be independent of at client --> create
* work on design and finalise implementation approach in PR48

**Comment by gkc** [comment]
Hi @murali-shris - please see also #756

**Comment by gkc** [comment]
Closing this issue as has been superseded by #756
