### ISSUE TITLE
IoT Demos for Santa Clara Event

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#690]
1. Integration of atPlatform with Badge from Dr.Bergmann
2. Floow integration

**Comment by ksanty** [comment]
@anthonyvprakash do we need to add to PR45?

**Comment by anthonyvprakash** [comment]
@ksanty  - we can keep this for the next Sprint

**Comment by ksanty** [comment]
Event completed
