### ISSUE TITLE
Our autobug GitHub action is failing to add new tickets to "Dev Eng Sprint Planning" project board

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#712]
**Describe the bug**
* Our autobug GitHub action is failing to add new tickets to "Dev Eng Sprint Planning" project board
* See https://github.com/atsign-foundation/at_client_sdk/actions/runs/3082689892/jobs/4982695756

**To Reproduce**
* Create a new issue in the `at_client_sdk` repo or `at_server` repo
* Likely to be failing in all repos

**Expected behavior**
Issue should be added to the "Dev Eng Sprint Planning Board", status 'Triage'

**Comment by cpswan** [comment]
Looks like something changed causing a permission problem with the token used (and the action isn't smart enough to error out):

```
Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:project'], but your token has only been granted the: ['admin:org', 'repo'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

**Comment by cpswan** [comment]
Tested with #716 now working again with extra [project] scope on the token.

https://github.com/leonsteinhaeuser/project-beta-automations/issues/53 raised so that the action author is aware that failures will happen but still show a 'successful' action run.
