### ISSUE TITLE
What is the process to keep testData cert.pem up to date?

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_client_sdk#724]
**Is your feature request related to a problem? Please describe.**

#590 introduced [cert.pem](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/at_functional_test/test/testData/cert.pem), which is a certificate for vip.ve.atsign.zone that expires on 13 Oct 2022:

<details><summary>certinfo for cert.pem</summary>

```
--- [cert.pem] ---
Version: 3
Serial Number: 348468537375923645201183287161454945746461
Signature Algorithm: SHA256-RSA
Type: end-entity
Issuer: CN=R3,O=Let's Encrypt,C=US
Validity
    Not Before: Jul 15 06:41:11 2022 UTC
    Not After : Oct 13 06:41:10 2022 UTC
Subject: CN=vip.ve.atsign.zone
DNS Names: vip.ve.atsign.zone
IP Addresses:
Key Usage: Digital Signature, Key Encipherment
Ext Key Usage: Server Auth, Client Auth
CA: false
```
</details>

Does this cert need to be kept up to date, and if so what's the plan to do that?

**Describe the solution you'd like**

Use automation similar to at_server [Refreshcerts](https://github.com/atsign-foundation/at_server/actions/workflows/refreshcerts.yml) workflow

**Describe alternatives you've considered**

We could create a standalone repo for certs and then use it as a submodule here and in at_server

**Comment by cpswan** [comment]
Assigned @kumarnarendra701 as he should be able to take existing actions/scripts and apply to this.

**Comment by kumarnarendra701** [comment]
@cpswan - I didn’t get the bandwidth to work on this task. Can you please move it to the next sprint?

**Comment by cpswan** [comment]
@kumarnarendra701 OK - moved to PR48

**Comment by kumarnarendra701** [comment]
@cpswan - Modified Refreshcerts script to sync with the latest script and raised PR with renewed certificate and script.
https://github.com/atsign-foundation/at_server/pull/1017
https://github.com/atsign-foundation/at_server/pull/1016

**Comment by cpswan** [comment]
@kumarnarendra701 https://github.com/atsign-foundation/at_server/pull/1017 certainly tidies up the existing script, but doesn't do what was asked for here, which is to have a similar script that updates the testData cert.pem certificate in *this* repo.

Moving to PR49

**Comment by kumarnarendra701** [comment]
@cpswan - Added Refreshcerts script to raise PR with renewed certificate and script. 
Workflow Script  PR - https://github.com/atsign-foundation/at_client_sdk/pull/777
Renewed cert PR - https://github.com/atsign-foundation/at_client_sdk/pull/776

**Comment by kumarnarendra701** [comment]
@cpswan - Can we close this?
