### ISSUE TITLE
end to end tests failing in at_client SDK

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#732]
**Describe the bug**
The end2end tests are failing in at_client sdk and following are the observations

- The Hive keystore and commit log keystore are being removed and the end of test and being re-initialized for every test. As a result the initial sync happens before all the tests in a given file (in some cases before each test). which is time consuming and also blocking the server.

- The empty batch requests are being sent to secondary server: https://github.com/atsign-foundation/at_client_sdk/issues/731

Temporary workaround:
--------------------------------
Added skip for the failing tests. A permanent fix would be to refactor the tests.

**Comment by sitaram-kalluri** [comment]
Spent 5 SP for the analysis in PR 46

**Comment by sitaram-kalluri** [comment]
- [ ] Refactor tests such that sync and creation of encryption keys happens at the beginning of all tests and clears at the end of all tests

**Comment by purnimavenkatasubbu** [comment]
Refactored the tests and pushed the changes to the [refactor_tests](https://github.com/atsign-foundation/at_client_sdk/tree/refactor_tests)

**Comment by purnimavenkatasubbu** [comment]
Refactored some more tests and pushed the changes to the same branch. [refactor_tests](https://github.com/atsign-foundation/at_client_sdk/tree/refactor_tests)

**Comment by purnimavenkatasubbu** [comment]
Refactoring tests are done, The tests are failing in the GitHub actions that need to be looked at.
Draft PR - (#774 )

**Comment by purnimavenkatasubbu** [comment]
There is a change in the workflow file that's a part of the PR. But the GitHub actions is considering the workflow file of the trunk branch instead of my local branch. Hence the tests are failing

**Comment by gkc** [comment]
@purnimavenkatasubbu That is not why the tests are failing, the GitHub actions is using the workflow file of your working branch

**Comment by purnimavenkatasubbu** [comment]
PR ready for review [PR](https://github.com/atsign-foundation/at_client_sdk/pull/774)
