### ISSUE TITLE
We currently have no tests for the 'fetchOfflineNotifications' flag

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#740]
**Describe the bug**
* A [recent PR](https://github.com/atsign-foundation/at_client_sdk/pull/701) added the fetchOfflineNotifications flag and made associated changes in NotificationServiceImpl. No tests were added for this feature.
* fetchOfflineNotification is currently only checked when the NotificationServiceImpl starts its Monitor. It should also be checked when it restarts its Monitor

**Expected behaviour**
* There should be tests which verify correct behaviour when fetchOfflineNotifications is false as well as when true (the default)
* Value of fetchOfflineNotifications should also be checked when NotificationServiceImple restarts its Monitor

**Background**
* When this ticket was originally filed, it looked as if setting this boolean to false was causing sync problem with the iot_receiver demo app. That problem now appears to have been coincidental, and likely caused by https://github.com/atsign-foundation/at_widgets/issues/546

**Comment by gkc** [comment]
Background: spent several hours yesterday with Colin & Kevin trying to figure out why their demo for the IOT expo had stopped working.

Eventually we figured out that the problem was that the client app wasn't syncing 

The only thing that had changed was that fetchOfflineNotifications was set to false. Setting it back to true resulted in everything working normally

We logically concluded that impl of fetchOfflineNotifications caused the problem somehow (even though that should be impossible). However my initial assumption of what the bug was, is incorrect

I will code up a small test harness to see if I can reproduce what Colin & Kevin were seeing. It is definitely the case that setting fetchOfflineNotifications to false caused the problem, but not at all clear as to why

**Comment by VJag** [comment]
My guess is, if we change the code and set fetchOfflineNotifications to false in the demo code it might work again. To me, it seems like a timing issue. Any idea if the test was done using a brand new atsign?

**Comment by gkc** [comment]
Don't know what the issue was, just that setting that flag to false resulted in client not syncing. Should be impossible, right?

**Comment by gkc** [comment]
When this ticket was originally filed, it looked as if setting this boolean to false was causing sync problem with the iot_receiver demo app. That sync problem was very likely a coincidence, possibly a side-effect of https://github.com/atsign-foundation/at_widgets/issues/546
