### ISSUE TITLE
Calling toString on the notification atKey has atsign twice prefixed and appended

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#772]
### Describe the bug

When atKey.toString is called on the key received in the notification callback, the resultant has the duplicate atsign's. 
For example, the key looks like `@baboon9blue:@baboon9blue:shared_key@81bored7@81bored7` instead of `@baboon9blue:shared_key@81bored7`.

### Steps to reproduce

1. Send a notification of the type messageType.key from the server 
2. On the at_client SDK, when the notification is received, call toString on the atKey and the resultant has atsign twice prefixed and appended.

Root Cause:

In the update_verb_handler.dart, we prefix and append the sharedWith and sharedBy to the key before sending the notification. So, the key in the notification looks like "@‎bob:phone@alice"; when logging the key, we have an atKey.toString which will again add sharedWith and sharedBy to the key. Hence the atsign's are shown twice

### Expected behavior

When toString is called on the atKey, the resultant should have atSign's prefixed and appended only once.

**Comment by sitaram-kalluri** [comment]
@gkc and @VJag : Below is the approach to fix this issue. Please review and let me know if there needs a modification in the approach.

1. In the update_verb_handler.dart and notify_verb_handler.dart, do not concatenate sharedWith and sharedBy atSigns to the key. In the update_verb_handler.dart, introduce a new variable that will hold the fully formed key (sharedWith:key@sharedBy) to insert/fetch the key from the key store.
   *  With the above changes in the notification key store, the AtNotification->notification field will have only a key ('phone') unlike earlier, a fully formed key ('@‎bob:phone@alice')

2. In the at_client_sdk, when returning the notification information from the monitor connection, to ensure backward compatibility, if the key starts with  '@' then return the key as is; else call atKey.toString to concatenate sharedWith and sharedBy to the key and return.

**Comment by gkc** [comment]
I don't believe this is the right way, as it changes existing behaviour.

Can we come up with a simpler solution?

**Comment by gkc** [comment]
This changes existing behaviour, so it feels risky. In particular, this bit:
> With the above changes in the notification key store, the AtNotification->notification field will have only a key ('phone') unlike earlier, a fully formed key ('@‎bob:phone@alice')

However clearly it is incorrect for the server to be prepending sharedWith and appending sharedBy to what is already a well-formed AtKey, so we need to do something.

It is strange that we have a clear design / intent inconsistency which has been around for a long time and yet it isn't affecting us except in this one situation ... can we lay out the problem a bit more clearly, explaining end to end (atsign1 client to atsign1 secondary to atsign2 secondary to atsign2 client) what is currently happening (a) for updates (b) for notifys ?

**Comment by sitaram-kalluri** [comment]
Spent 3 SP finding the root cause of the issue and a fix in PR-49. Moving to PR-50 for the remaining work.

**Comment by gkc** [comment]
@sitaram-kalluri Can you pick this up in PR56 please?

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri Can you pick this up in PR56 please?

@gkc: Sure

**Comment by sitaram-kalluri** [comment]
The changes are merged to the trunk branch. Pending publishing the package

**Comment by gkc** [comment]
Closing as publication is imminent
