### ISSUE TITLE
Secure element: Initial design and implementation of at_chops interface

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#784]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756 for overall context

### Describe the solution you'd like

See https://github.com/atsign-foundation/at_client_sdk/issues/756#issuecomment-1296441973

**Comment by murali-shris** [comment]
initial pull request
https://github.com/atsign-foundation/at_libraries/pull/245

**Comment by gkc** [comment]
Added "8SP" yesterday as a reflection of work completed during this sprint. @murali-shris can you estimate for this sprint now? Maybe list out the high-level tasks that remain to be done? (Note that #756 links to other tickets which I've created for the integration of at_chops into the various libraries (at_lookup, at_client, at_client_mobile, at_onboarding_cli, at_onboarding_flutter)

**Comment by murali-shris** [comment]
Implementation done in PR 50
- used encryption algo implementation from https://pub.dev/packages/encrypt and https://pub.dev/packages/crypton
- introduced objects for representing various keys such as AES, public private key pair,pkam key pair, cram secret in lib/src/key
- added abstract class AtEncryptionAlgorithm for encryption/decryption, AtSigningAlgorithm for data signing and verification, - 
 - AtHashingAlgorithm for hashing in lib/src/algorithm/at_algorithm.dart
- RSA asymmetric encryption is implemented in lib/src/algorithm/rsa_encryption_algo.dart
- generating aes key, IV and key pairs is implemented in lib/src/util/at_chops_util.dart
- all encryption, signing and hashing methods are exposed via lib/src/at_chops_base.dart
- Pkam signing algorithm is implemented in lib/src/algorithm/pkam_signing_algo.dart
- Signing algorithm using at_encryption key pair is implemented in lib/src/algorithm/default_signing_algo.dart
- addressed review comments

**Comment by murali-shris** [comment]
Tasks to be done in PR51
* AES encryption/decryption and IV in at_chops_impl
* Encryption/Decryption metadata object to be returned
* close out further review comments and publish version 1.0.0

**Comment by murali-shris** [comment]
https://pub.dev/packages/at_chops
published initial version.
