### ISSUE TITLE
secure element: at_lookup refactoring to use at_chops

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#788]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756

### Describe the solution you'd like

See https://github.com/atsign-foundation/at_client_sdk/issues/756

**Comment by murali-shris** [comment]
Changes done in https://github.com/atsign-foundation/at_libraries/pull/253/files.
PR under review

**Comment by murali-shris** [comment]
> Changes done in https://github.com/atsign-foundation/at_libraries/pull/253/files. PR under review

changes are complete. Currently new method in atlookup pkamAuthenticate which uses at_chops will not be called. Once at_client_mobile uptake is complete which will set at_chops instance to at_lookup, replace deprecated method with pkamAuthenticate

**Comment by murali-shris** [comment]
added published version of at_chops to at_lookup pubspec and merged to trunk.

**Comment by murali-shris** [comment]
> > Changes done in https://github.com/atsign-foundation/at_libraries/pull/253/files. PR under review
> 
> changes are complete. Currently new method in atlookup pkamAuthenticate which uses at_chops will not be called. Once at_client_mobile uptake is complete which will set at_chops instance to at_lookup, replace deprecated method with pkamAuthenticate

at_lookup to be published later along with at_client_mobile uptake
