### ISSUE TITLE
secure element: at_client refactoring to use at_chops

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#789]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756

### Describe the solution you'd like

See https://github.com/atsign-foundation/at_client_sdk/issues/756

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_client_sdk/pull/809
PR under review

Pending:
More unit tests
check for any other methods in at client making use of encryption or pkam private key
replace signing methods with new implementation

**Comment by murali-shris** [comment]
> #809 PR under review
> 
> Pending: More unit tests check for any other methods in at client making use of encryption or pkam private key replace signing methods with new implementation

all changes are complete. Added a feature flag in preferences useAtChops=false. Flag will be turned on once app testing is good.

**Comment by murali-shris** [comment]
minor review comments have to be addressed.

**Comment by murali-shris** [comment]
open review comment related to at_chops init is pending. 
https://github.com/atsign-foundation/at_client_sdk/pull/809#discussion_r1047034072

**Comment by murali-shris** [comment]
Outcome of the discussion with @gkc and @VJag 
* creating atChops instance is responsibility of onboarding flow in atclient_mobile/onboarding_service. atChops needs not be instantiated within atclient.
* during switchAtSign, atClient instance will be retrieved from cache. Hence no need to init atChops again
* Need flag in at lookup to use atChops or use fallback code for backward compatibility
* nice to have features. isOnboarded/onBoardWithKeys methods in at_client.

**Comment by murali-shris** [comment]
created a feature request in backlog
https://github.com/atsign-foundation/at_client_sdk/issues/866

**Comment by murali-shris** [comment]
merged the change to trunk. Publishing of at_client will be done once @purnimavenkatasubbu resolves pub score issues
