### ISSUE TITLE
Error in decrypt 

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#79]
I was logged in as @darkcabaretuncertain , when I received any notification , I was getting error while decrypting the value.

I am facing this issue on production server . 
On staging server I tried with different atsigns and it was working.

![decrypt_error](https://user-images.githubusercontent.com/74917871/111440912-d06c4780-872c-11eb-8b01-60befe5379aa.png)

**Comment by murali-shris** [comment]
@sachins-geekyants are you still facing this issue ?

**Comment by sachins-geekyants** [comment]
@murali-shris I haven't checked it recently , I will get back to you after testing it on trunk branch.

**Comment by sachins-geekyants** [comment]
@murali-shris still getting this issue after we reset atsign.

![Screenshot 2021-08-23 at 3 25 33 PM](https://user-images.githubusercontent.com/74917871/130428398-5f785e14-b17a-487f-b4cc-9f8d15d40ad1.png)
