### ISSUE TITLE
secure element: at_client_mobile refactoring to use at_chops

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#790]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756

### Describe the solution you'd like

See https://github.com/atsign-foundation/at_client_sdk/issues/756

**Comment by gkc** [comment]
Moving to Backlog as we won't get to it this sprint

**Comment by murali-shris** [comment]
Pull request:
https://github.com/atsign-foundation/at_client_sdk/pull/863/files
Pending:
- update published version of at_lookup and at_client
- sanity check with apps

**Comment by murali-shris** [comment]
Pending

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client_mobile: v3.2.8
