### ISSUE TITLE
secure element: at_onboarding_cli refactoring to use at_chops

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#791]
### Is your feature request related to a problem? Please describe.

See https://github.com/atsign-foundation/at_client_sdk/issues/756

### Describe the solution you'd like

See https://github.com/atsign-foundation/at_client_sdk/issues/756

**Comment by gkc** [comment]
Moving to Backlog as we won't get to it this sprint

**Comment by murali-shris** [comment]
Code changes done. Unit tests in progress

**Comment by murali-shris** [comment]
PR merged https://github.com/atsign-foundation/at_libraries/pull/281
and at_onboarding_cli  v1.2.3 published
