### ISSUE TITLE
Sync: Define sync contracts by test cases

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#794]
### Is your feature request related to a problem? Please describe.

See #793 

This task is to cover the work involved in defining the individual contracts that, when strung together, make up the overall sync contract

### Describe the solution you'd like

Define contracts (groups of test cases) for
- [x] (Client) How items are added to the 'uncommitted' queue on the client side (upon data store operations)
- [x] (Client) How the client processes that uncommitted queue (while sending updates to server) - e.g. how is the queue ordered, how is it de-duped, etc
- [x] (Server) How the server processes updates from the client (including the responses it generates) and what the expectations are - i.e. can we reject? what happens when we reject? and more
- [x] (Server) How items are added to the commit log on the server such that they are available for sync to the clients
- [x] (Server) How the server processes that log (when sending updates to client) - e.g. again ordering, de-duping, etc
- [x] (Client) How the client processes updates from the server - can the client reject? under what conditions? what happens upon a rejection?
- [x] The 7th contract is the contract for precisely how the client and server exchange information. Currently this is implemented using the batch verb and has state like 'syncInProgress' and 'isInSync'.

**Comment by gkc** [comment]
@VJag Feel free to either leave this as it is (single ticket) or add individual tickets for each of the subtasks as you wish

**Comment by gkc** [comment]
@VJag can you tick off whatever's been completed in the task list above, please?

**Comment by VJag** [comment]
- On the client side, done with the design of test cases
- Implemented majority of the test cases (https://github.com/atsign-foundation/at_client_sdk/pull/807)
- On the server side design of the test scenarios is over. We are in the process of refining them. Implementation of the server tests will be taken up in this sprint. (https://github.com/atsign-foundation/at_server/blob/sync_unit_tests/packages/at_secondary_server/test/sync_unit_test.dart)

**Comment by gkc** [comment]
Great! We can close this ticket as completed.
