### ISSUE TITLE
Sync: Write the unit (most), functional (some) and end-to-end (few) tests which verify the sync contracts

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#795]
### Is your feature request related to a problem? Please describe.

See #793 

This task is to cover the work involved in verifying the individual contracts that, when strung together, make up the overall sync contract. (Definition of those contracts is covered by #794)

### Describe the solution you'd like

Verify the contracts by implementing the test cases for
- [x] (Client) How items are added to the 'uncommitted' queue on the client side (upon data store operations)
- [x] (Client) How the client processes that uncommitted queue (while sending updates to server) - e.g. how is the queue ordered, how is it de-duped, etc
- [x] (Server) How the server processes updates from the client (including the responses it generates) and what the expectations are - i.e. can we reject? what happens when we reject? and more
- [x] (Server) How items are added to the commit log on the server such that they are available for sync to the clients
- [x] (Server) How the server processes that log (when sending updates to client) - e.g. again ordering, de-duping, etc
- [x] (Client) How the client processes updates from the server - can the client reject? under what conditions? what happens upon a rejection?
- [x] The 7th contract is the contract for precisely how the client and server exchange information. Currently this is implemented using the batch verb and has state like 'syncInProgress' and 'isInSync'.
- [x] PR review and merge to trunk

**Comment by gkc** [comment]
@VJag Feel free to either leave this as it is (single ticket) or add individual tickets for each of the subtasks as you wish

**Comment by gkc** [comment]
@VJag @srieteja @purnimavenkatasubbu Please can you (1) link branch(es) and/or PR(s) to this ticket and (2) provide brief summary of where we've got to and what's left to do?

**Comment by purnimavenkatasubbu** [comment]
Unit tests have been completed for the first 2 groups in the file sync_new_test.dart and the changes are available in the following PR [sync_unit_tests](https://github.com/atsign-foundation/at_client_sdk/pull/807).

Pending Work 
1) To continue writing the remaining unit tests
2) Raise enhancement requests for the tests that need a change in the SDK.

**Comment by purnimavenkatasubbu** [comment]
- Client-side unit tests are implemented and the changes are merged to trunk.
- Server-side unit tests implementation is done. Tests can be found in the PR [sync_unit_tests](https://github.com/atsign-foundation/at_server/pull/1098)

Only PR code review and merging to trunk is pending in the ticket. Updating SP to 3

**Comment by purnimavenkatasubbu** [comment]
PR merged to trunk. [sync_tests](https://github.com/atsign-foundation/at_server/pull/1098). Hence closing the issue.
