### ISSUE TITLE
Refactor the sync unit tests to increase code coverage

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_client_sdk#798]
### Is your feature request related to a problem? Please describe.

1. Refactor the existing sync scenario unit tests and write new scenarios to increase the code coverage

### Describe the solution you'd like

The new sync unit test scenarios are added to the following branch: https://github.com/atsign-foundation/at_client_sdk/tree/sync_unit_tests

**Comment by sitaram-kalluri** [comment]
Spent 8 SP in PR-49 doing a thorough analysis on the sync and framing the unit tests: Following branch to unit tests: https://github.com/atsign-foundation/at_client_sdk/tree/sync_unit_tests

**Comment by gkc** [comment]
Thanks @kalluriramkumar !!! Closing this ticket as complete as we now have #794 and #795 to cover the ongoing work
