### ISSUE TITLE
Should have callback or stream to receive the message

### ISSUE THREAD

**Issue by lovung** [atsign-foundation/at_client_sdk#8]
I read the code but don't see any method to receive the message automatically. For an application likes a chat app, this is the important method to replace the message queue (because we don't have any server in a p2p connection).

**Comment by murali-shris** [comment]
@sarika01 Please add at_chats widget version available in pub.dev and close this issue

**Comment by sarika01** [comment]
Latest version of chat library on pub.dev:
at_chat_flutter: ^1.0.1
