### ISSUE TITLE
docs uplift: Review content section by section and create tickets as required

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#800]
### Is your feature request related to a problem? Please describe.

See #799 for overall context

### Describe the solution you'd like

In pairs or trios, review content docs.atsign.com section by section, creating tickets as required for corrections, clarifications or missing content

### High-level tasks (please add additional tasks here!)
- [ ] Divide up the docs into sections which are amenable to review in 60-90 minutes by 2-3 people working together
- [ ] Review section 1
- [ ] Review section 2
- [ ] ... Review section N

**Comment by gkc** [comment]
Marking as High priority following conversation with @XavierChanth last week

**Comment by gkc** [comment]
Timeboxing to 8SP during this sprint between @gkc and any other volunteers they can enlist

**Comment by gkc** [comment]
We did some initial work in PR50 but mostly this needs to roll over into next sprint

**Comment by gkc** [comment]
No progress in PR51

**Comment by ksanty** [comment]
@gkc is this still a P1?

**Comment by xavierchanth** [comment]
Docs site is in a good place for now, apkam may change that.
