### ISSUE TITLE
Azbil IoT Demo for High Rise Buildings

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/at_client_sdk#801]
- [x] Define the best use case for the demo for Azbil ( workshop on Nov 18, in the Bay Area)
- [x] Build demo for Azbil

**Comment by cconstab** [comment]
- [x] Demo a computer, that allowed a relay to switch on/off using AtPlatform..

- [ ] Stretch goal Standalone and with connected to the Internet

**Comment by cconstab** [comment]
Demo went well but needs more dev work if we work more with Azbil
