### ISSUE TITLE
Rethinking the use of enums to represent state

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_client_sdk#816]
I noticed that the use of enums has become slightly problematic due to different features needing slightly different ways of expressing what is essentially the type of operation occurring for an event.

For example, we have the OperationEnum which has `update, delete` as well as the legacy `append, remove`.

In addition to that, in at_persistence_secondary_server, we have `UPDATE, DELETE, UPDATE_META, UPDATE_ALL` for which I assume the various `UPDATE*` enums are all considered as `update` when converted to an operation enum.

Then, when working on KeyStream, I needed the ability to extend the enum and add an additional option: `init, update, delete`. Where `init` is the operation that occurs upon initialization of the key stream, and is used to identify an initial fetch of the keys.

Most recently, I noticed that a similar operation enum was created for the Intents demo. I am opening up this issue for the purposes of thinking how we can simplify operation complexity, maybe switching to a hierarchical class based approach:

```mermaid
classDiagram
class AtOperation {
  AtOperation.fromCommitOp(String commitOp)
  AtOperation.fromString(String operation)
}
AtOperation <|-- AtInitOperation : For KeyStream
AtOperation <|-- AtDeleteOperation
AtOperation <|-- AtUpdateOperation
AtUpdateOperation <|-- AtUpdateSingleOperation : For CommitOp
AtUpdateOperation <|-- AtUpdateAllOperation : For CommitOp
AtUpdateOperation <|-- AtUpdateMetaOperation : For CommitOp
```
- Assume every class has an empty nameless constructor, and a toString() which returns the same string that AtOperation.fromString() would use for creation.
- `AtUpdateSingleOperation` may not be the correct name, it is meant to represent `CommitOp.UPDATE`
- A disadvantage to this approach is that we can no longer use switch/case statements. However, what may be even more useful is:
```dart
if(operation is AtUpdateOperation) {
 // Captures all of:
 // - AtUpdateOperation
 //   - AtUpdateSingleOperation
 //   - AtUpdateAllOperation
 //   - AtUpdateMetaOperation
}
```

Open to suggestions and feedback, what I am looking for here is a solution that fits all needs.

**Comment by ksanty** [comment]
@XavierChanth I think we said we'd add 2SP's to arch call discussions due to the # of people involved.

**Comment by ksanty** [comment]
@XavierChanth is this the issue that we needed an urgent label?
