### ISSUE TITLE
Collection abstract class and it's implementation

### ISSUE THREAD

**Issue by sachins-geekyants** [atsign-foundation/at_client_sdk#826]
### Is your feature request related to a problem? Please describe.

This ticket is part of the collections library work. The scope of this ticket is to implement the contracts defined in the collections spec.

### Describe the solution you'd like

- [x] Implement the share, unshare and list people shared with the functionality of the collections library
- [ ] Implement partial success/failure handling

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by ksanty** [comment]
@VJag I think you mentioned adding 8 SP's to this card?  Please confirm.

**Comment by sachins-geekyants** [comment]
Added a draft PR with implementation of share, unshare : https://github.com/atsign-foundation/at_client_sdk/pull/848.
Partial success/failure handling is not included in this PR.

**Comment by sachins-geekyants** [comment]
Collection has been written from scratch with the methods contracts.
Partial success is not yet implemented.
