### ISSUE TITLE
KeyInfo should include description and commitOp

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_client_sdk#833]
### Is your feature request related to a problem? Please describe.

The KeyInfo currently gives information about the key, syncDirection, and conflictInfo. 

### Describe the solution you'd like

KeyInfo should include a description saying about the cause. For example, "Key is an invalid/Bad key ", "Delete of key is successful".
Also, KeyInfo should include the commitOp of the key, Whether it is an UPDATE, DELETE, or UPDATE_META operation.

**Comment by sitaram-kalluri** [comment]
Along with adding CommitOp. to the KeyInfo, the deprecated the onDone callback.

The onDone callback is a redundant of SyncProgressListener in notifying the sync progress. Hence deprecated the onDone callback and removed the usage of onDone callback in the at_client package in unit tests, functional tests and end2end tests.

Spent additional two days in PR-54 to find the usages and refactor the tests and raise git issues in other repos which has usages of SyncService.onDone.

Total story points spent in PR-54 : 5SP

**Comment by sitaram-kalluri** [comment]
PR awaiting review. No Pending work. Hence marked to 0 SP

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client v3.0.55
