### ISSUE TITLE
test: functional test atclient_sharedkey_test.dart is occasionally failing

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#840]
### Describe the bug

functional test atclient_sharedkey_test.dart is occasionally failing

### Steps to reproduce

Has happened at least twice in the past three days. It eventually fails after a three minute timeout. 

### Expected behavior

test should pass. Likely a race condition related to checking if sync is complete.

**Comment by gkc** [comment]
This test still occasionally fails; would be good if this ticket can be picked up this sprint. Going to re-estimate as 3SP though. @VJag can you figure out who to assign this to?

**Comment by purnimavenkatasubbu** [comment]
I could not replicate the issue I'll look at the failed tests in Github actions and add a fix. Moving to the PR54

**Comment by purnimavenkatasubbu** [comment]
Not able to find the cause of the failing test. I checked the logs in the GitHub actions it just shows a timeout exception after 3 minutes.

**Comment by gkc** [comment]
I'd like us to get to the bottom of this in PR56. Collectively we have a lot of wasted time re-running PR checks which fail sporadically.

**Comment by purnimavenkatasubbu** [comment]
Did not get a chance to debug the issue this sprint. Moving to PR57

**Comment by purnimavenkatasubbu** [comment]
Raised a dummy PR and Ran the tests 3 to 4 times to see if the atclient_sharedkey_test fails. It did not fail. I'll check a few more times to see if the test fails again.
https://github.com/atsign-foundation/at_client_sdk/actions/runs/4372879118

**Comment by purnimavenkatasubbu** [comment]
I did not get a chance to debug the issue in this sprint. I had other p1 tasks to work on.

**Comment by purnimavenkatasubbu** [comment]
Raised a PR for the test. #1017

**Comment by purnimavenkatasubbu** [comment]
The fix for the issue is merged into the trunk. Closing the issue as fixed. [PR](https://github.com/atsign-foundation/at_client_sdk/pull/1017)
