### ISSUE TITLE
rollback path and async version in pubspec

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#878]
### Describe the bug

After at_client 3rd party dependencies were upgraded to latest version,  3rd party  packages path and async version are causing an issue in app "flutter pub get" since flutter_test uses lower versions of these packages

### Steps to reproduce

* Upgrade to latest version of at_client(3.0.50) in pubspec and run flutter pub get in at_client_mobile or any app

### Expected behavior

* flutter pub get should run without any errors

**Comment by purnimavenkatasubbu** [comment]
Reverted back to the old versions. Here's the [PR](https://github.com/atsign-foundation/at_client_sdk/pull/879)

**Comment by purnimavenkatasubbu** [comment]
at_client: 3.051 is published with the change. closing the ticket
