### ISSUE TITLE
add a check in github build pipeline for pull requests that contain unformatted code

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#880]
### Is your feature request related to a problem? Please describe.

* Currently unformatted code can make their way into trunk branch. This can affect the pub score for published packages.

### Describe the solution you'd like

* Add a check in github build pipeline to check for dart formatting in code and prevent merge.

### Describe alternatives you've considered

* run dartfmt command and check for git status output
* check for dart analyze output
* check for pub score
https://pub.dev/help/scoring 
section "Calculating pub points prior to publishing"

**Comment by murali-shris** [comment]
@cpswan I will create a example for unformatted code and attach further details here

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_client_sdk/tree/unformatted_code_sample
commit for unformatted code: https://github.com/atsign-foundation/at_client_sdk/commit/85ca7f5d837331d898aa064218259ccc3faf715a
murali@murali-Latitude-3460:~/git/at_protocol/at_client_sdk/packages/at_client$ dart format .
Formatted lib/src/client/at_client_impl.dart
Formatted 146 files (1 changed) in 1.79 seconds.

**Comment by murali-shris** [comment]
check pub score through pana. This one is nice to have but not a pressing requirement. Compare actual pub score with latest version of published package vs final output of below command.
murali@murali-Latitude-3460:~/tmp/at_client$ dart pub global run pana .
INFO       Running `/usr/lib/dart/bin/dart --no-analytics --version`...
INFO       Running `flutter --suppress-analytics --no-version-check --version --machine`...
WARNING    pana might update or modify files in `.`.
           Analysis will begin in 15 seconds, hit CTRL+C to abort it.
           To remove this message, use `--no-warning`.
INFO       Running `git rev-parse --show-toplevel`...
INFO       Running `/usr/lib/dart/bin/dart --no-analytics pub get --no-example`...
INFO       Running `/usr/lib/dart/bin/dart --no-analytics pub outdated --json --up-to-date --no-dev-dependencies --no-dependency-overrides`...
INFO       Analyzing package...
INFO       Running `/usr/lib/dart/bin/dart --no-analytics analyze --format machine lib`...
INFO       Running `git init`...
INFO       Running `git remote add origin https://github.com/atsign-foundation/at_client_sdk`...
INFO       Running `git remote show origin`...
INFO       Running `git fetch --depth 1 --no-recurse-submodules origin trunk`...
INFO       Running `git ls-tree -r --name-only --full-tree origin/trunk`...
INFO       Running `git show origin/trunk:packages/at_client/example/pubspec.yaml`...
INFO       Running `git show origin/trunk:packages/at_client/pubspec.yaml`...
INFO       Running `git show origin/trunk:packages/at_client_mobile/example/pubspec.yaml`...
INFO       Running `git show origin/trunk:packages/at_client_mobile/pubspec.yaml`...
INFO       Running `git show origin/trunk:tests/at_end2end_test/pubspec.yaml`...
INFO       Running `git show origin/trunk:tests/at_functional_test/pubspec.yaml`...
INFO       Running `/usr/lib/dart/bin/dart --no-analytics format --output=none --set-exit-if-changed /tmp/pana_MSLWBW/./lib`...

## ✓ Follow Dart file conventions (30 / 30)
### [*] 10/10 points: Provide a valid `pubspec.yaml`


### [*] 5/5 points: Provide a valid `README.md`


### [*] 5/5 points: Provide a valid `CHANGELOG.md`


### [*] 10/10 points: Use an OSI-approved license

Detected license: `BSD-3-Clause`.

## ✓ Provide documentation (10 / 10)
### [*] 10/10 points: Package has an example


## ✓ Platform support (20 / 20)
### [*] 20/20 points: Supports 5 of 6 possible platforms (**iOS**, **Android**, Web, **Windows**, **MacOS**, **Linux**)

* ✓ Android
* ✓ iOS
* ✓ Windows
* ✓ Linux
* ✓ MacOS

These platforms are not supported:

<details>
<summary>
Package not compatible with platform Web
</summary>

Because:
* `package:at_client/at_client.dart` that imports:
* `package:at_client/src/listener/sync_progress_listener.dart` that imports:
* `package:at_client/src/service/sync/sync_status.dart` that imports:
* `package:at_client/src/service/sync_service_impl.dart` that imports:
* `package:at_utils/at_utils.dart` that imports:
* `package:at_utils/at_logger.dart` that imports:
* `package:at_utils/src/logging/atsignlogger.dart` that imports:
* `package:at_utils/src/logging/handlers.dart` that imports:
* `dart:io`
</details>

## ✗ Pass static analysis (20 / 30)
### [~] 20/30 points: code has no errors, warnings, lints, or formatting issues

<details>
<summary>
/tmp/pana_MSLWBW/lib/src/client/at_client_impl.dart doesn't match the Dart formatter.
</summary>

To format your files run: `dart format .`
</details>

## ✓ Support up-to-date dependencies (20 / 20)
### [*] 10/10 points: All of the package dependencies are supported in the latest version

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`archive`]|`^3.3.5`|3.3.5|3.3.5|
|[`async`]|`^2.9.0`|2.10.0|2.10.0|
|[`at_base2e15`]|`^1.0.0`|1.0.0|1.0.0|
|[`at_chops`]|`^1.0.0`|1.0.0|1.0.0|
|[`at_commons`]|`^3.0.34`|3.0.34|3.0.34|
|[`at_lookup`]|`^3.0.35`|3.0.35|3.0.35|
|[`at_persistence_secondary_server`]|`^3.0.44`|3.0.44|3.0.44|
|[`at_persistence_spec`]|`^2.0.10`|2.0.10|2.0.10|
|[`at_utf7`]|`^1.0.0`|1.0.0|1.0.0|
|[`at_utils`]|`^3.0.11`|3.0.11|3.0.11|
|[`collection`]|`^1.16.0`|1.17.0|1.17.0|
|[`convert`]|`^3.0.2`|3.1.1|3.1.1|
|[`cron`]|`^0.5.1`|0.5.1|0.5.1|
|[`crypto`]|`^3.0.1`|3.0.2|3.0.2|
|[`crypton`]|`^2.1.0`|2.1.0|2.1.0|
|[`encrypt`]|`^5.0.1`|5.0.1|5.0.1|
|[`hive`]|`^2.2.3`|2.2.3|2.2.3|
|[`http`]|`^0.13.5`|0.13.5|0.13.5|
|[`internet_connection_checker`]|`^1.0.0+1`|1.0.0+1|1.0.0+1|
|[`meta`]|`^1.8.0`|1.8.0|1.8.0|
|[`path`]|`^1.8.2`|1.8.3|1.8.3|
|[`uuid`]|`^3.0.7`|3.0.7|3.0.7|

<details><summary>Transitive dependencies</summary>

|Package|Constraint|Compatible|Latest|
|:-|:-|:-|:-|
|[`_fe_analyzer_shared`]|-|52.0.0|52.0.0|
|[`analyzer`]|-|5.4.0|5.4.0|
|[`args`]|-|2.3.1|2.3.1|
|[`asn1lib`]|-|1.4.0|1.4.0|
|[`boolean_selector`]|-|2.1.1|2.1.1|
|[`clock`]|-|1.1.1|1.1.1|
|[`coverage`]|-|1.6.1|1.6.1|
|[`file`]|-|6.1.4|6.1.4|
|[`frontend_server_client`]|-|3.2.0|3.2.0|
|[`glob`]|-|2.1.1|2.1.1|
|[`http_multi_server`]|-|3.2.1|3.2.1|
|[`http_parser`]|-|4.0.2|4.0.2|
|[`io`]|-|1.0.3|1.0.3|
|[`js`]|-|0.6.5|0.6.6|
|[`logging`]|-|1.1.0|1.1.0|
|[`matcher`]|-|0.12.14|0.12.14|
|[`mime`]|-|1.0.4|1.0.4|
|[`mocktail`]|-|0.3.0|0.3.0|
|[`mutex`]|-|3.0.1|3.0.1|
|[`node_preamble`]|-|2.0.1|2.0.1|
|[`package_config`]|-|2.1.0|2.1.0|
|[`pointycastle`]|-|3.6.2|3.6.2|
|[`pool`]|-|1.5.1|1.5.1|
|[`pub_semver`]|-|2.1.3|2.1.3|
|[`shelf`]|-|1.4.0|1.4.0|
|[`shelf_packages_handler`]|-|3.0.1|3.0.1|
|[`shelf_static`]|-|1.1.1|1.1.1|
|[`shelf_web_socket`]|-|1.0.3|1.0.3|
|[`source_map_stack_trace`]|-|2.1.1|2.1.1|
|[`source_maps`]|-|0.10.11|0.10.11|
|[`source_span`]|-|1.9.1|1.9.1|
|[`stack_trace`]|-|1.11.0|1.11.0|
|[`stream_channel`]|-|2.1.1|2.1.1|
|[`string_scanner`]|-|1.2.0|1.2.0|
|[`term_glyph`]|-|1.2.1|1.2.1|
|[`test`]|-|1.22.2|1.22.2|
|[`test_api`]|-|0.4.18|0.4.18|
|[`test_core`]|-|0.4.22|0.4.22|
|[`typed_data`]|-|1.3.1|1.3.1|
|[`vm_service`]|-|9.4.0|10.0.0|
|[`watcher`]|-|1.0.2|1.0.2|
|[`web_socket_channel`]|-|2.3.0|2.3.0|
|[`webkit_inspection_protocol`]|-|1.2.0|1.2.0|
|[`yaml`]|-|3.1.1|3.1.1|
</details>

To reproduce run `dart pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides`.

[`archive`]: https://pub.dev/packages/archive
[`async`]: https://pub.dev/packages/async
[`at_base2e15`]: https://pub.dev/packages/at_base2e15
[`at_chops`]: https://pub.dev/packages/at_chops
[`at_commons`]: https://pub.dev/packages/at_commons
[`at_lookup`]: https://pub.dev/packages/at_lookup
[`at_persistence_secondary_server`]: https://pub.dev/packages/at_persistence_secondary_server
[`at_persistence_spec`]: https://pub.dev/packages/at_persistence_spec
[`at_utf7`]: https://pub.dev/packages/at_utf7
[`at_utils`]: https://pub.dev/packages/at_utils
[`collection`]: https://pub.dev/packages/collection
[`convert`]: https://pub.dev/packages/convert
[`cron`]: https://pub.dev/packages/cron
[`crypto`]: https://pub.dev/packages/crypto
[`crypton`]: https://pub.dev/packages/crypton
[`encrypt`]: https://pub.dev/packages/encrypt
[`hive`]: https://pub.dev/packages/hive
[`http`]: https://pub.dev/packages/http
[`internet_connection_checker`]: https://pub.dev/packages/internet_connection_checker
[`meta`]: https://pub.dev/packages/meta
[`path`]: https://pub.dev/packages/path
[`uuid`]: https://pub.dev/packages/uuid
[`_fe_analyzer_shared`]: https://pub.dev/packages/_fe_analyzer_shared
[`analyzer`]: https://pub.dev/packages/analyzer
[`args`]: https://pub.dev/packages/args
[`asn1lib`]: https://pub.dev/packages/asn1lib
[`boolean_selector`]: https://pub.dev/packages/boolean_selector
[`clock`]: https://pub.dev/packages/clock
[`coverage`]: https://pub.dev/packages/coverage
[`file`]: https://pub.dev/packages/file
[`frontend_server_client`]: https://pub.dev/packages/frontend_server_client
[`glob`]: https://pub.dev/packages/glob
[`http_multi_server`]: https://pub.dev/packages/http_multi_server
[`http_parser`]: https://pub.dev/packages/http_parser
[`io`]: https://pub.dev/packages/io
[`js`]: https://pub.dev/packages/js
[`logging`]: https://pub.dev/packages/logging
[`matcher`]: https://pub.dev/packages/matcher
[`mime`]: https://pub.dev/packages/mime
[`mocktail`]: https://pub.dev/packages/mocktail
[`mutex`]: https://pub.dev/packages/mutex
[`node_preamble`]: https://pub.dev/packages/node_preamble
[`package_config`]: https://pub.dev/packages/package_config
[`pointycastle`]: https://pub.dev/packages/pointycastle
[`pool`]: https://pub.dev/packages/pool
[`pub_semver`]: https://pub.dev/packages/pub_semver
[`shelf`]: https://pub.dev/packages/shelf
[`shelf_packages_handler`]: https://pub.dev/packages/shelf_packages_handler
[`shelf_static`]: https://pub.dev/packages/shelf_static
[`shelf_web_socket`]: https://pub.dev/packages/shelf_web_socket
[`source_map_stack_trace`]: https://pub.dev/packages/source_map_stack_trace
[`source_maps`]: https://pub.dev/packages/source_maps
[`source_span`]: https://pub.dev/packages/source_span
[`stack_trace`]: https://pub.dev/packages/stack_trace
[`stream_channel`]: https://pub.dev/packages/stream_channel
[`string_scanner`]: https://pub.dev/packages/string_scanner
[`term_glyph`]: https://pub.dev/packages/term_glyph
[`test`]: https://pub.dev/packages/test
[`test_api`]: https://pub.dev/packages/test_api
[`test_core`]: https://pub.dev/packages/test_core
[`typed_data`]: https://pub.dev/packages/typed_data
[`vm_service`]: https://pub.dev/packages/vm_service
[`watcher`]: https://pub.dev/packages/watcher
[`web_socket_channel`]: https://pub.dev/packages/web_socket_channel
[`webkit_inspection_protocol`]: https://pub.dev/packages/webkit_inspection_protocol
[`yaml`]: https://pub.dev/packages/yaml


### [*] 10/10 points: Package supports latest stable Dart and Flutter SDKs


## ✓ Support sound null safety (20 / 20)
### [*] 20/20 points: Package and dependencies are fully migrated to null safety!


Points: 120/130.

**Comment by cpswan** [comment]
#945 fixes this, and is presently in review. Adjusted to 1 SP.
