### ISSUE TITLE
intermittent unit/functional test failures in at_client

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_client_sdk#981]
### Describe the bug

1.unit test failure in full_stack_test.dart
https://github.com/atsign-foundation/at_client_sdk/actions/runs/4531205164/jobs/7981075022?pr=978

2. functional test failure in commit_log_compaction_test.dart
https://github.com/atsign-foundation/at_client_sdk/actions/runs/4534311709/jobs/7988326981

### Steps to reproduce

n/a

### Expected behavior

* unit and functional tests should consistently pass

**Comment by murali-shris** [comment]
unit test failure fixed by @gkc 
in PR https://github.com/atsign-foundation/at_client_sdk/pull/980

**Comment by murali-shris** [comment]
For issue # 2, I ran the commit_log_compaction_test with local server in a loop (20 times)

Able to replicate the issue the issue once after multiple attempts

**Comment by gkc** [comment]
Another occasional unit test failure (e.g. in [this](https://github.com/atsign-foundation/at_client_sdk/actions/runs/4892123843/attempts/1) action run) is the following

```
test/sync_new_test.dart: A group of test to verify sync conflict resolution A test to verify when sync conflict info when key present in uncommitted entries and in server response of sync (failed)
  INFO|2023-05-05 09:53:39.964249|HiveBase|commit_log_38229722d63f456a35120d98f43873a0b9e5bbb2182def930834332b30c118cb initialized successfully 
  
  INFO|2023-05-05 09:53:39.965729|HiveBase|38229722d63f456a35120d98f43873a0b9e5bbb2182def930834332b30c118cb initialized successfully 
  
  INFO|2023-05-05 09:53:40.006089|SyncService (@hiro)|984319571|Returning serverCommitId 3 
  
  INFO|2023-05-05 09:53:40.007212|SyncService (@hiro)|187671533|Returning serverCommitId 3 
  
  INFO|2023-05-05 09:53:40.023724|SyncService (@hiro)|709749291|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app; syncRequest.onDone : null 
  
  INFO|2023-05-05 09:53:40.024165|SyncService (@hiro)|1014060890|Returning serverCommitId 3 
  
  Expected: SyncStatus:<SyncStatus.success>
    Actual: SyncStatus:<SyncStatus.started>
  
  package:matcher                 expect
  test/sync_new_test.dart 2874:9  main.<fn>.<fn>.<fn>
  Callback called more times than expected (1).
```

**Comment by purnimavenkatasubbu** [comment]
With the latest changes to the functional_tests, This test isn't failing. Added syncOptions to wait till the key is synced. Changes are in the branch [issue#981](https://github.com/atsign-foundation/at_client_sdk/tree/issue%23981). Will raise a PR and close the ticket.

**Comment by purnimavenkatasubbu** [comment]
functional_tests have been refactored recently and the tests no longer fail.
